# Basic information
site_name: 高二九班(对口计算机)
site_url: https://buhaoqi.github.io
site_author: 村长
site_description: >-
  2026年河北省中职对口升学考试计算机类专业考试学习交流。

# Copyright
copyright: Copyright &copy; 2023 - 2025 村长 <a href="https://beian.mps.gov.cn/#/query/webSearch?code=13040202001048" target="_blank">冀公网安备13040202001048号</a><a href="https://beian.miit.gov.cn/#/Integrated/index" target="_blank">冀ICP备2025101972号-1</a>
    

# Configuration
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  # - blog:
    # - blog_dir: /blog/
  #- minify:
      #minify_html: true
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - 首页: 
    - 考试大纲: ./index.md
    - 村长讲C#: ./cs.md
  - C#文档:
    - 考试大纲: ./csharp-docs/index.md
    - 问题汇总: ./csharp-docs/00-questions.md
    - 起步:
      - 认识C#: ./csharp-docs/01-get-started/01-what-csharp-is.md
      - 环境搭建: ./csharp-docs/01-get-started/02-environment-setup.md
      - 解决方案与项目: ./csharp-docs/01-get-started/03-solution-project.md
      - 创建解决方案与项目: ./csharp-docs/01-get-started/04-create-solution-project.md
      - 文件模版: ./csharp-docs/01-get-started/04-file-template.md
      - 变量与常量: csharp-docs/01-get-started/05-variable-constant.md
      - 输入输出: csharp-docs/01-get-started/06-input-and-output.md
      - 命名空间: csharp-docs/01-get-started/07-namespace.md
      - Solution: csharp-docs/01-get-started/08-solution-project.md
    - 数据类型:
      - 数据类型: csharp-docs/02-data-type/01-data-type.md
      - 整数类型: csharp-docs/02-data-type/02-integer.md
      - 浮点数类型(7道): csharp-docs/02-data-type/03-float.md
      - 字符类型: csharp-docs/02-data-type/04-char.md
      - 字符串类型: csharp-docs/02-data-type/05-string.md
      - 布尔类型: csharp-docs/02-data-type/06-boolean.md
      - 数组: csharp-docs/02-data-type/07-array.md
      - struct: csharp-docs/02-data-type/08-struct.md
      - enum: csharp-docs/02-data-type/09-enum.md
      - delegate: csharp-docs/02-data-type/10-delegate.md
      - interface: csharp-docs/02-data-type/11-interface.md
      - 数据类型转换(20道): csharp-docs/02-data-type/15-convert-data-type.md
    - 运算符:
      - 赋值运算符: csharp-docs/03-operators/01-assignment-operators.md
      - 算数运算符: csharp-docs/03-operators/02-arithmetic-operators.md
      - 关系运算符: csharp-docs/03-operators/03-comparison-operators.md
      - 逻辑运算符: csharp-docs/03-operators/04-logical-operators.md
    - 语句:
      - 条件语句: csharp-docs/04-statements/01-conditional-statements.md
      - for循环: csharp-docs/04-statements/02-for-loop-statement.md
      - while循环: csharp-docs/04-statements/03-while-loop-statement.md
      - do-while循环语句: csharp-docs/04-statements/04-do-while-loop-statement.md
    - 方法:
      - 方法基础: csharp-docs/05-methods/01-method-basics.md
      - public关键词: csharp-docs/05-methods/02-method-modifier-public.md
      - private关键词: csharp-docs/05-methods/03-method-modifier-private.md
      - internal关键词: csharp-docs/05-methods/04-method-modifier-internal.md
      - static关键词: csharp-docs/05-methods/05-method-modifier-static.md
      - 构造函数: csharp-docs/05-methods/09-constructor.md
      - INT方法: csharp-docs/05-methods/10-int-methods.md
      - 字符串方法: csharp-docs/05-methods/11-string-methods.md
      - FLOAT方法: csharp-docs/05-methods/12-float-methods.md
      - 数组方法: csharp-docs/05-methods/13-array-methods.md
    - 类:
      - 类与对象: csharp-docs/06-classes/01-class-and-object.md
      - 属性与方法: csharp-docs/06-classes/02-property-and-method.md
      - 继承: csharp-docs/06-classes/03-inheritance.md
      - 多态: csharp-docs/06-classes/04-polymorphism.md
      - 抽象类与接口: csharp-docs/06-classes/05-abstract-class-and-interface.md
    - 算法:
      - 排序算法: csharp-docs/07-algorithms/01-sorting-algorithms.md
      - 查找算法: csharp-docs/07-algorithms/02-searching-algorithms.md
      - 递归算法: csharp-docs/07-algorithms/03-recursion.md
      - 分治算法: csharp-docs/07-algorithms/04-divide-and-conquer.md
      - 贪心算法: csharp-docs/07-algorithms/05-greedy-algorithm.md
      - 动态规划: csharp-docs/07-algorithms/06-dynamic-programming.md
  - C#教程:
    - 首页: csharp-tutorial/index.md
    - 新人起步:
      - 01-安装Visual Studio: csharp-tutorial/01.md
      - 02-创建解决方案: csharp-tutorial/02.md
      - 03-手写Hello World: csharp-tutorial/03.md
      - 04-文件模板: csharp-tutorial/04.md
      - 05-数据类型与变量: csharp-tutorial/05.md
      - 06-常量: csharp-tutorial/06.md
      - 07-Console输入输出: csharp-tutorial/07.md
      - 08-命名空间: csharp-tutorial/08.md
    - 数据类型(初学乍道):
      - 09-if条件语句: csharp-tutorial/09.md
      - 10-整数类型: csharp-tutorial/10.md
      - 11-浮点数类型: csharp-tutorial/11.md
      - 12-字符类型: csharp-tutorial/12.md
      - 13-字符串类型: csharp-tutorial/13.md
      - 14-字符串方法1: csharp-tutorial/14.md
      - 15-字符串方法2: csharp-tutorial/15.md
      - 16-项目实战:字符串: csharp-tutorial/16.md
    - 运算符:
      - 18-赋值运算符: csharp-tutorial/18.md
      - 19-算数运算符: csharp-tutorial/19.md
      - 20-关系运算符: csharp-tutorial/20.md
      - 21-逻辑运算符: csharp-tutorial/21.md
      - 22-三目运算符: csharp-tutorial/22.md
      - 23-特殊运算符: csharp-tutorial/23.md
      - 24-运算符优先级: csharp-tutorial/24.md
    - 数据类型进阶:
      - 08-命名空间: csharp-tutorial/08.md
      - 09-if条件语句: csharp-tutorial/09.md
      - 10-整数类型: csharp-tutorial/10.md
      - 11-浮点数类型: csharp-tutorial/11.md
      - 12-字符类型: csharp-tutorial/12.md
      - 13-字符串类型: csharp-tutorial/13.md
      - 14-字符串方法1: csharp-tutorial/14.md
      - 15-字符串方法2: csharp-tutorial/15.md
      - 16-项目实战:字符串: csharp-tutorial/16.md
      - 17-布尔类型: csharp-tutorial/17.md
    
    - 25-数据类型转换: csharp-tutorial/25.md
    - 26-switch条件语句: csharp-tutorial/26.md
    - 27-for循环语句: csharp-tutorial/27.md
    - 28-while循环语句: csharp-tutorial/28.md
    - 29-数组: csharp-tutorial/29.md
    - 30-数组方法1: csharp-tutorial/30.md
    - 31-数组方法2: csharp-tutorial/31.md
    - 32-项目实战：学生成绩管理系统: csharp-tutorial/32.md
    - 34-list类型(list): csharp-tutorial/34.md
    - 35-集合类型(Dictionary): csharp-tutorial/35.md
    - 36-Dictionary: csharp-tutorial/36.md
    - 37-集合类型(HashSet): csharp-tutorial/37.md
    - 38-集合类型(Stack): csharp-tutorial/38.md
    - 39-集合类型(Queue): csharp-tutorial/39.md
    - 40-集合类型(LinkedList): csharp-tutorial/40.md
    - 41-: csharp-tutorial/41.md
    - 42-: csharp-tutorial/42.md
    - 43-: csharp-tutorial/43.md
    - 44-: csharp-tutorial/44.md
    - 45-: csharp-tutorial/45.md
    - 46-: csharp-tutorial/46.md
    - 47-: csharp-tutorial/47.md
    - 48-: csharp-tutorial/48.md
    - 49-: csharp-tutorial/49.md
    - 50-: csharp-tutorial/50.md
    - 51-: csharp-tutorial/51.md
    - 52-: csharp-tutorial/52.md
    - 53-: csharp-tutorial/53.md
    - 54-: csharp-tutorial/54.md
    - 55-: csharp-tutorial/55.md
    - 56-: csharp-tutorial/56.md
    - 57-: csharp-tutorial/57.md
    - 58-: csharp-tutorial/58.md
    - 59-: csharp-tutorial/59.md
    - 60-: csharp-tutorial/60.md
    - 61-: csharp-tutorial/61.md
    - 62-: csharp-tutorial/62.md
    - 63-: csharp-tutorial/63.md
    - 64-: csharp-tutorial/64.md
    - 65-: csharp-tutorial/65.md
  - Windows Forms:
    - 考试大纲: windows-form/index.md
    - 起步: windows-form/02-get-started.md
    - 窗体与控件: windows-form/index.md
    - 事件处理: windows-form/index.md
    - 数据绑定: windows-form/index.md
    - 菜单与工具栏: windows-form/index.md
    - 对话框: windows-form/index.md
  - MySQL文档:
    - 考试大纲: mysql/index.md
    - MySQL的基本概念: mysql/01-basic-concept.md
    - MySQL的安装与配置: mysql/02-install-config.md
    - 登录与退出MySQL: mysql/03-login-logout.md
    - 操作数据库结构:
      - 创建数据库:  mysql/04-create-database.md
      - 删除数据库: mysql/05-drop-database.md
      - 修改数据库名: mysql/06-alter-database.md
      - 查询数据库: mysql/07-show-database.md
      - 选择数据库: mysql/08-use-database.md
    - 操作表结构: 
      - 创建表结构: mysql/09-create-table.md
      - 复制表结构: mysql/09-copy-table.md
      - 删除表结构: mysql/10-drop-table.md
      - 修改表结构: mysql/11-alter-table.md
      - 查询表结构: mysql/12-show-table.md
      - 重命名表: mysql/13-rename-table.md
    - 操作数据: 
      - 添加数据: mysql/14-insert-data.md
      - 删除数据: mysql/15-delete-data.md
      - 修改数据: mysql/16-update-data.md
      - 查询数据: mysql/17-select-data.md
    - 数据类型: mysql/18-data-type.md
    - 数据完整性约束: mysql/19-constraint.md
    - 索引: mysql/20-index.md
    - 视图: mysql/21-view.md
    - 数据库设计: mysql/22-database-design.md
    - 数据库安全性: mysql/23-database-security.md
    - 数据库的备份与恢复: mysql/24-database-backup-recovery.md
    - 字符串函数:
      - Length()函数: mysql/function/string-length.md
      - Upper()函数: mysql/function/string-upper.md
      - Lower()函数: mysql/function/string-lower.md
      - Left()函数: mysql/function/string-left.md
      - Right()函数: mysql/function/string-right.md
      - Rtrim()函数: mysql/function/string-rtrim.md
      - Substring()函数: mysql/function/string-substring.md
      - Locate()函数: mysql/function/string-locate.md
      - Position()函数: mysql/function/string-position.md
      - Reverse()函数: mysql/function/string-reverse.md
      - concat()函数: mysql/function/string-concat.md
    - 数学函数: 
      - abs(): mysql/function/math-abs.md
      - rand(): mysql/function/math-rand.md
      - ceil(): mysql/function/math-ceil.md
      - floor(): mysql/function/math-floor.md
      - round(): mysql/function/math-round.md
      - truncate(): mysql/function/math-truncate.md
      - pow(): mysql/function/math-pow.md
      - sqrt(): mysql/function/math-sqrt.md
      - mod(): mysql/function/math-mod.md
      - PI(): mysql/function/math-pi.md
    - 聚合函数: mysql/function/aggregate-function.md
    - 日期函数:
      - now(): mysql/function/date-now.md
      - curdate(): mysql/function/date-curdate.md
      - curtime(): mysql/function/date-curtime.md
      - date_format(): mysql/function/date-date-format.md
      - year(): mysql/function/date-year.md
      - month(): mysql/function/date-month.md
      - day(): mysql/function/date-day.md
      - hour(): mysql/function/date-hour.md
      - minute(): mysql/function/date-minute.md
      - second(): mysql/function/date-second.md
      - format: mysql/function/date-format.md
    - 其他函数:
      - if(): mysql/function/others-if.md
      - IFNULL(): mysql/function/others-ifnull.md
      - version(): mysql/function/others-version.md
      - version(): mysql/function/other-field.md
      - version(): mysql/function/other-format.md
  - Excel:
    - 考试大纲: excel/index.md
    - 题库: excel/exercises.md
    - Excel的基本概念: excel/01.md
    - 工作簿的基本操作: excel/02.md
    - 工作表的基本操作: excel/03.md
    - 单元格的基本操作: excel/04.md
    - 公式与函数: excel/05.md
    - 使用图表: excel/06.md
    - 数据清单管理: excel/07.md
    - 页面设置与打印: excel/08.md
  - 计算机基础:
    - 考试大纲: computer-basics/index.md
    - 计算机进制: computer-basics/number-system.md
    - 计算机的组成: computer-basics/02-computer-structure.md
    - 操作系统: computer-basics/03-operating-system.md
    - Windows操作系统: computer-basics/04-windows-os.md
    - Linux操作系统: computer-basics/05-linux-os.md
    - 网络基础: computer-basics/06-network-basics.md
    - 网络协议: computer-basics/07-network-protocols.md
    - 网络设备: computer-basics/08-network-devices.md
  - Windows操作系统:
    - 考试大纲: windows10/index.md
    - 操作系统基础: windows10/01.md
    - Windows 10基础: windows10/02.md
    - Windows 10的文件管理: windows10/03.md
    - Windows 10的控制面板: windows10/04.md
    - Windows 10的任务管理器: windows10/05.md
    - Windows 10的实用工具: windows10/06.md
    - Windows 10的磁盘管理: windows10/07.md
    - 中文输入: windows10/08.md
  - 暑期作业:
    - 6月21日:For循环笔记: exercises/csharp/0621.md
    - 6月22日:For循环练习: exercises/csharp/0622.md
    - 6月23日:变量与常量: exercises/csharp/0623-variables.md
    - 6月24日:while循环: exercises/csharp/0624-while-loop.md
    - 6月25日:算数运算符: exercises/csharp/0625.md
    - 6月26日:练习(41道): exercises/csharp/0626.md
    - 6月27日:练习(16道): exercises/csharp/0627.md
    - 6月28日:练习(18道): exercises/csharp/0628.md
    - 6月29日:IF练习(40道): exercises/csharp/0629.md
    - 6月30日:SWITCH练习(10道): exercises/csharp/0630.md
    - 7月01日:三目运算符练习(10道): exercises/csharp/0701.md
    - 7月02日:读书笔记1: exercises/csharp/0702.md
    - 7月03日:读书笔记2: exercises/csharp/0703.md
    - 7月04日:读书笔记3: exercises/csharp/0704.md
    - 7月05日:读书笔记4: exercises/csharp/0705.md
    - 7月06日:第5章类的基本概念: exercises/csharp/0706.md
    - 7月07日:类练习题: exercises/csharp/0707.md
    - 7月08日:类练习: exercises/csharp/0708.md
    # - 7月09日:第6章练习题: exercises/csharp/0709.md
    # - 7月10日:第7章深入理解类: exercises/csharp/0710.md
    # - 7月11日:第7章练习题: exercises/csharp/0711.md
    - 7月15日:计算机基础知识1: exercises/csharp/0715.md
    - 7月16日:计算机基础知识2: exercises/csharp/0716.md
    - 7月17日:计算机基础知识3: exercises/csharp/0717.md
    - 7月18日:操作系统概述: exercises/csharp/0718.md
    - 7月19日:Win10基础: exercises/csharp/0719.md
  - C#练习题:
    - 首页: csharp-exercises/index.md
    - 起步:
      - 环境搭建: csharp-exercises/01-get-started/01-environment-setup.md
      - 认识C#: csharp-exercises/01-get-started/02-what-csharp-is.md
      - Hello World(2道): csharp-exercises/01-get-started/03-hello-world.md
      - 变量与常量(14道): csharp-exercises/01-get-started/05-variable-constant.md
      - 输入输出: csharp-exercises/01-get-started/06-input-and-output.md
      - 命名空间: csharp-exercises/01-get-started/07-namespace.md
    - 数据类型:
      - 数据类型(33道): csharp-exercises/02-data-type/01-data-type.md
      - 整数类型(40道): csharp-exercises/02-data-type/02-integer.md
      - 浮点数类型(11道): csharp-exercises/02-data-type/03-float.md
      - 字符类型(6道): csharp-exercises/02-data-type/04-char.md
      - 字符串类型(49道): csharp-exercises/02-data-type/05-string.md
      - 布尔类型: csharp-exercises/02-data-type/06-boolean.md
      - 数组(49道): csharp-exercises/02-data-type/07-array.md
      - 数据类型转换(20道): csharp-exercises/02-data-type/15-convert-data-type.md
    - 运算符:
      - 赋值运算符: csharp-exercises/03-operators/01-assignment-operators.md
      - 算数运算符(41道): csharp-exercises/03-operators/02-arithmetic-operators.md
      - 关系运算符(16道): csharp-exercises/03-operators/03-comparison-operators.md
      - 逻辑运算符(18道): csharp-exercises/03-operators/04-logical-operators.md
      - 三目运算符: csharp-exercises/03-operators/05-ternary-operator.md
      - 特殊运算符: csharp-exercises/03-operators/06-special-operators.md
      - 运算符优先级: csharp-exercises/03-operators/07-operator-precedence.md
    - 语句:
      - 条件语句: csharp-exercises/04-statements/01-if.md
      - switch语句: csharp-exercises/04-statements/02-switch.md
      - for循环: csharp-exercises/04-statements/03-for-loop-statement.md
      - while循环: csharp-exercises/04-statements/04-while-loop-statement.md
      - do-while循环语句: csharp-exercises/04-statements/05-do-while-loop-statement.md
      - 嵌套分支语句: csharp-exercises/04-statements/06-nested-branching-statements.md
    - 方法:
      - 基础练习: csharp-exercises/05-methods/01-method-basics.md
      - public练习: csharp-exercises/05-methods/02-method-modifier-public.md
      - static练习: csharp-exercises/05-methods/03-method-modifier-static.md
      - 构造函数练习: csharp-exercises/05-methods/09-constructor.md
      - INT方法: csharp-exercises/05-methods/01-int-methods.md
      - 字符串方法: csharp-exercises/05-methods/02-string-methods.md
      - FLOAT方法: csharp-exercises/05-methods/03-float-methods.md
      - 数组方法: csharp-exercises/05-methods/04-array-methods.md
      - 数组方法: csharp-exercises/05-methods/04-array-methods.md
  - 编程英语:
      - 单词: english/index.md 