# Basic information
site_name: 高二九班(对口计算机)
site_url: https://buhaoqi.github.io
site_author: 村长
site_description: >-
  2026年河北省中职对口升学考试计算机类专业考试学习交流。

# Copyright
copyright: Copyright &copy; 2023 - 2025 村长 <a href="https://beian.mps.gov.cn/#/query/webSearch?code=13040202001048" target="_blank">冀公网安备13040202001048号</a><a href="https://beian.miit.gov.cn/#/Integrated/index" target="_blank">冀ICP备2025101972号-1</a>
    

# Configuration
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    # - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  # - blog:
    # - blog_dir: /blog/
  #- minify:
      #minify_html: true
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - 首页: index.md
  - C#教程:
    - 考试大纲: csharp/index.md
    - 环境搭建: csharp/01-environment-setup.md
    - 认识C#: csharp/02-what-csharp-is.md
    - Hello World(2道): csharp/03-hello-world.md
    - 数据类型(2道): csharp/04-data-type.md
    - 变量与常量(20道): csharp/05-variable-constant.md
    - 输入输出: csharp/06-input-and-output.md
    - 赋值运算符: csharp/07-assignment-operators.md
    - 算数运算符(29道): csharp/08-arithmetic-operators.md
    - 整数类型(35道): csharp/09-integer.md
    - 浮点数类型(7道): csharp/10-float.md
    - 数据类型转换(20道): csharp/11-convert-data-type.md
    - INT方法: csharp/12-int-methods.md
    - FLOAT方法: csharp/13-float-methods.md
    - 字符类型: csharp/14-char.md
    - 字符串类型(49道): csharp/15-string.md
    - 布尔类型: csharp/16-boolean.md
    - 关系运算符: csharp/17-comparison-operators.md
    - 逻辑运算符: csharp/18-logical-operators.md
    - 条件语句: csharp/19-conditional-statements.md
    - 循环语句: csharp/20-loop-statements.md
    - 数组: csharp/21-array.md
    - 数组方法: csharp/22-array-methods.md
  - MySQL文档:
    - 考试大纲: mysql/index.md
    - MySQL的基本概念: mysql/01-basic-concept.md
    - MySQL的安装与配置: mysql/02-install-config.md
    - 登录与退出MySQL: mysql/03-login-logout.md
    - 操作数据库结构:
      - 创建数据库:  mysql/04-create-database.md
      - 删除数据库: mysql/05-drop-database.md
      - 修改数据库名: mysql/06-alter-database.md
      - 查询数据库: mysql/07-show-database.md
      - 选择数据库: mysql/08-use-database.md
    - 操作表结构: 
      - 创建表结构: mysql/09-create-table.md
      - 删除表结构: mysql/10-drop-table.md
      - 修改表结构: mysql/11-alter-table.md
      - 查询表结构: mysql/12-show-table.md
      - 重命名表: mysql/13-rename-table.md
    - 操作数据: 
      - 添加数据: mysql/14-insert-data.md
      - 删除数据: mysql/15-delete-data.md
      - 修改数据: mysql/16-update-data.md
      - 查询数据: mysql/17-select-data.md
    - 数据类型: mysql/18-data-type.md
    - 数据完整性约束: mysql/19-constraint.md
    - 索引: mysql/20-index.md
    - 视图: mysql/21-view.md
    - 数据库设计: mysql/22-database-design.md
    - 数据库安全性: mysql/23-database-security.md
    - 数据库的备份与恢复: mysql/24-database-backup-recovery.md
    - 字符串函数:
      - Length()函数: mysql/function/string-length.md
      - Upper()函数: mysql/function/string-upper.md
      - Lower()函数: mysql/function/string-lower.md
      - Left()函数: mysql/function/string-left.md
      - Right()函数: mysql/function/string-right.md
      - Rtrim()函数: mysql/function/string-rtrim.md
      - Substring()函数: mysql/function/string-substring.md
      - Locate()函数: mysql/function/string-locate.md
      - Position()函数: mysql/function/string-position.md
      - Reverse()函数: mysql/function/string-reverse.md
      - concat()函数: mysql/function/string-concat.md
    - 数学函数: 
      - abs(): mysql/function/math-abs.md
      - rand(): mysql/function/math-rand.md
      - ceil(): mysql/function/math-ceil.md
      - floor(): mysql/function/math-floor.md
      - round(): mysql/function/math-round.md
      - truncate(): mysql/function/math-truncate.md
      - pow(): mysql/function/math-pow.md
      - sqrt(): mysql/function/math-sqrt.md
      - mod(): mysql/function/math-mod.md
      - PI(): mysql/function/math-pi.md
    - 聚合函数: mysql/function/aggregate-function.md
    - 日期函数:
      - now(): mysql/function/date-now.md
      - curdate(): mysql/function/date-curdate.md
      - curtime(): mysql/function/date-curtime.md
      - date_format(): mysql/function/date-date-format.md
      - year(): mysql/function/date-year.md
      - month(): mysql/function/date-month.md
      - day(): mysql/function/date-day.md
      - hour(): mysql/function/date-hour.md
      - minute(): mysql/function/date-minute.md
      - second(): mysql/function/date-second.md
      - format: mysql/function/date-format.md
    - 其他函数:
      - if(): mysql/function/others-if.md
      - IFNULL(): mysql/function/others-ifnull.md
      - version(): mysql/function/others-version.md
      - version(): mysql/function/other-field.md
      - version(): mysql/function/other-format.md
  
    