# Basic information
site_name: 高二九班(对口计算机)
site_url: https://buhaoqi.github.io
site_author: 村长
site_description: >-
  2026年河北省中职对口升学考试计算机类专业考试学习交流。

# Copyright
copyright: Copyright &copy; 2023 - 2025 村长 <a href="https://beian.mps.gov.cn/#/query/webSearch?code=13040202001048" target="_blank">冀公网安备13040202001048号</a><a href="https://beian.miit.gov.cn/#/Integrated/index" target="_blank">冀ICP备2025101972号-1</a>
    

# Configuration
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  # - blog:
    # - blog_dir: /blog/
  #- minify:
      #minify_html: true
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - 首页: 
    - 考试大纲: ./index.md
  - C#教程:
    - 考试大纲: csharp-tutorial/index.md
    - VS快捷键: csharp-tutorial/vs-shortcuts.md
    - 新人起步:
      - 1.安装Visual Studio: csharp-tutorial/01-get-started/01-installation.md
      - 2.创建第一个程序: csharp-tutorial/01-get-started/02-create-first-project.md
      - 3.类与对象: csharp-tutorial/01-get-started/03-class-object.md
      - 4.手写Hello World: csharp-tutorial/01-get-started/04-hello-world.md
      - 5.分号与注释: csharp-tutorial/01-get-started/05-semicolon-and-comments.md
      - 6.数据类型入门: csharp-tutorial/01-get-started/06-data-type-basics.md
      - 7.字面量变量与常量: csharp-tutorial/01-get-started/07-literal-variable-const.md
      - 8.变量的命名规范: csharp-tutorial/01-get-started/08-naming-conventions-for-variables.md
    - 数据类型基础(初学乍练):
      - 9.整数类型: csharp-tutorial/02-data-types/01-integer-type.md
      - 10.浮点数类型: csharp-tutorial/02-data-types/02-float-type.md
      - 11.var关键字: csharp-tutorial/02-data-types/03-var-keyword.md
      - 12.字符类型: csharp-tutorial/02-data-types/04-char-type.md
      - 13.字符串类型: csharp-tutorial/02-data-types/05-string-type.md
      - 14.字符串转数值: csharp-tutorial/02-data-types/06-string-to-number.md
      - 15.数据的输入与输出: csharp-tutorial/02-data-types/07-output-input.md
    - 运算符基础(初窥门径):
      - 16-算数运算符: csharp-tutorial/03-operators/01-arithmetic-operators.md
      - 17-比较运算符: csharp-tutorial/03-operators/02-comparison-operators.md
      - 18-字符集: csharp-tutorial/03-operators/03-charset.md
      - 19-逻辑运算符: csharp-tutorial/03-operators/04-logical-operators.md
      - 20-赋值运算符: csharp-tutorial/03-operators/05-assignment-operators.md
      - 21-自增自减运算符: csharp-tutorial/03-operators/06-auto-increment-decrement-operators.md
    - 控制语句(渐入佳境):
      - 21-if条件语句: csharp-tutorial/04-statements/01-conditional-statements.md
      - 22-switch条件语句: csharp-tutorial/04-statements/02-switch-statement.md
      - 23-for循环语句: csharp-tutorial/04-statements/03-for-loop-statement.md
      - 24-while循环语: csharp-tutorial/04-statements/04-while-loop-statement.md
      - 25-条件运算符: csharp-tutorial/03-operators/07-conditional-operators.md
      - 25-break与continue语句: csharp-tutorial/04-statements/05-break-continue-statements.md
      - 26-跳转语句: csharp-tutorial/04-statements/06-jump-statements.md
    - 数值进阶:
      - 27-格式化数值: csharp-tutorial/05-numbers/01-format-number.md
    - 字符串进阶:
      - 28-格式化字符串: csharp-tutorial/06-string/01-format-string.md
      - 29-字符串插值: csharp-tutorial/06-string/02-interpolated-string.md
      - 30-字符串的基础操作: csharp-tutorial/06-string/03-string-operations.md
      - 31-字符串连接: csharp-tutorial/06-string/04-string-concatenation.md
      - 32-字符串的常用方法2: csharp-tutorial/06-string/05-string-methods2.md
    - 数组:
      - 33-数组基础知识: csharp-tutorial/07-array/01-array-basics.md
      - 34-数组操作: csharp-tutorial/07-array/02-array-operations.md
      - 35-数组的遍历: csharp-tutorial/07-array/03-foreach-loop-statement.md
      - 36-数组的方法1: csharp-tutorial/07-array/04-array-methods.md
      - 37-数组的方法2: csharp-tutorial/07-array/05-array-methods2.md
    - 数据类型进阶:
      - 39-类型转换运算符: csharp-tutorial/03-operators/08-typeof.md
      - 40-运算符优先级: csharp-tutorial/03-operators/09-youxianji.md
      - 41-数据类型转换: csharp-tutorial/08-data-types-intermediate/01-type-conversion.md
      - 42-struct类型: csharp-tutorial/08-data-types-intermediate/02-struct.md
      - 43-enum类型: csharp-tutorial/08-data-types-intermediate/03-enum.md
      - 44-delegate类型: csharp-tutorial/08-data-types-intermediate/04-delegate.md
      - 45-dynamic类型: csharp-tutorial/08-data-types-intermediate/05-dynamic.md
      - 46-List类型: csharp-tutorial/08-data-types-intermediate/06-lists.md
      - 47-Dictionary类型: csharp-tutorial/08-data-types-intermediate/07-dictionary.md
      - 48-interface类型: csharp-tutorial/08-data-types-intermediate/08-interface.md
    - 方法:
      - 1-方法是什么: csharp-tutorial/05-methods/01-what-is-method.md
      - 2-方法的基础操作: csharp-tutorial/05-methods/02-method-operation.md
      - 3-方法参数: csharp-tutorial/05-methods/02-method-parameters.md
      - 4-方法返回值: csharp-tutorial/05-methods/03-method-return-values.md
      - 5-方法重载: csharp-tutorial/05-methods/04-method-overloading.md
      - 6-静态方法与实例方法: csharp-tutorial/05-methods/05-static-instance-methods.md
    - 类:
      - 37-面向对象编程: csharp-tutorial/06-class/01-oop.md
      - 38-初识类与对象: csharp-tutorial/06-class/02-what-class-is.md
      - 39-类与字段: csharp-tutorial/06-class/03-class-fields.md
      - 40-类的属性: csharp-tutorial/06-class/04-class-properties.md
      - 41-类与方法: csharp-tutorial/06-class/05-class-methods.md
      - 42-类与构造函数: csharp-tutorial/06-class/06-class-constructor.md
      - 43-类的访问修饰符: csharp-tutorial/06-class/07-class-access-modifiers.md
      - 44-类的析构函数: csharp-tutorial/06-class/08-class-destructor.md
      - 45-类的静态成员: csharp-tutorial/06-class/09-class-static-members.md
      - 46-类的静态方法: csharp-tutorial/06-class/10-class-static-methods.md
      - 47-类的静态属性: csharp-tutorial/06-class/11-class-static-properties.md
      - 48-抽象类与接口: csharp-tutorial/06-class/12-abstract-interface.md
      - 49-类的构造函数: csharp-tutorial/06-class/08-class-constructor.md
      - 50-类的析构函数: csharp-tutorial/06-class/09-class-destructor.md
      - 51-类的静态成员: csharp-tutorial/06-class/10-class-static-members.md
      - 52-类的静态方法: csharp-tutorial/06-class/11-class-static-methods.md
      - 53-类的静态属性: csharp-tutorial/06-class/12-class-static-properties.md
      - 54-DateTime类型: csharp-tutorial/06-class/01-datetime.md
      - 55-Random类型: csharp-tutorial/06-class/02-random.md
    - 三大特性:
      - 封装: csharp-tutorial/07-encapsulation/01-what-is-encapsulation.md
      - 继承: csharp-tutorial/08-inheritance/01-what-is-inheritance.md
      - 多态: csharp-tutorial/09-polymorphism/01-what-is-polymorphism.md
    - 附:DOTNET相关知识:
      - 01-DOTNET简介: csharp-tutorial/11-dotnet/01-introduction.md
      - 02-DOTNET的安装: csharp-tutorial/11-dotnet/02-installation.md
      - 03-DOTNET的运行时: csharp-tutorial/11-dotnet/03-runtime.md   
      - 04-DOTNET的SDK: csharp-tutorial/11-dotnet/04-sdk.md
      - 05-DOTNET的命令行工具: csharp-tutorial/11-dotnet/05-cli.md
      - 06-DOTNET的项目结构: csharp-tutorial/11-dotnet/06-project-structure.md
      - 06-System: csharp-tutorial/11-dotnet/06-system.md
      - 06-System.Int32: csharp-tutorial/11-dotnet/06-system-int32.md
      - 06-System.Int32元数据: csharp-tutorial/11-dotnet/06-system-int32-meta.md
      - 06-System.Type: csharp-tutorial/11-dotnet/06-system-type.md
      - 06-System.Enum: csharp-tutorial/11-dotnet/06-system-enum.md
      - 06-System.Enum.GetValues(): csharp-tutorial/11-dotnet/06-system-enum-getvalues.md
      - 07-DOTNET的包管理系统: csharp-tutorial/11-dotnet/07-package-management.md
  - 算法:
    - 考试大纲: csharp-algorithm/index.md
    - 算法概述: csharp-algorithm/01-overview.md
    - 📚基础数学算法:
      - 1.累加与累乘: csharp-algorithm/math/sum-and-product.md
      - 2.最值与均值: csharp-algorithm/math/min-max-and-average.md
      - 3.公约数与素数: csharp-algorithm/math/gcd-and-prime.md
      - 4.阶乘与斐波那契数列: csharp-algorithm/math/factorial-and-fibonacci.md
    - 📚查找算法:
      - 5.顺序查找: csharp-algorithm/search/sequential-search.md
      - 6.二分查找: csharp-algorithm/search/binary-search.md
    - 📚排序算法:
      - 7.冒泡排序: csharp-algorithm/sort/bubble-sort.md
      - 8.选择排序: csharp-algorithm/sort/selection-sort.md
      - 9.插入排序: csharp-algorithm/sort/insertion-sort.md
    - 📚递归算法:
      - 10.阶乘: csharp-algorithm/recursion/factorial.md
      - 11.斐波那契数列: csharp-algorithm/recursion/fibonacci-sequence.md
      - 12.汉诺塔: csharp-algorithm/recursion/tower-of-hanoi.md
      - 13.二分查找递归版: csharp-algorithm/search/binary-search-recursion.md
    - 📚字符串与加密算法:
      - 14.回文数判断: csharp-algorithm/string/palindrome-check.md
      - 15.字符串加密: csharp-algorithm/string/string-encryption.md
  - C#图形:
    - 考试大纲: csharp-graphics/index.md
    - 图形编程概述: csharp-graphics/01-overview.md
    - Drawing类介绍: csharp-graphics/02-drawing.md
    - 绘制基本图形: csharp-graphics/03-drawing-basic-shapes.md
    - 绘制文本: csharp-graphics/04-drawing-text.md
    - 处理图像: csharp-graphics/05-image-processing.md
    - 事件与交互: csharp-graphics/06-events-and-interaction.md
  - WinForms:
    - 考试大纲: csharp-winform/index.md
    - 项目文件: csharp-winform/projects.md
    - WinForms简介: csharp-winform/00-overview.md
    - 01.窗体与控件: csharp-winform/01-forms-controls.md
    - 02.窗体的属性: csharp-winform/02-form-properties.md
    - 03.窗体的方法: csharp-winform/03-form-methods.md
    - 04.窗体的事件: csharp-winform/04-form-events.md
    - 05.窗体的创建和使用: csharp-winform/05-form-creation-and-usage.md
    - 06.标签属性: csharp-winform/06-labels.md
    - 07.文本框属性: csharp-winform/07-textboxes.md
    - 08.文本框事件: csharp-winform/08-textbox-events.md
    - 09.按钮属性: csharp-winform/09-buttons.md
    - 10.按钮事件: csharp-winform/10-button-events.md
    - 11.组合框属性: csharp-winform/11-comboboxes.md
    - 12.列表框属性: csharp-winform/12-listboxes.md
    - 13.单选按钮属性: csharp-winform/13-radiobuttons.md
    - 14.复选框属性: csharp-winform/14-checkboxes.md
    - 15.滚动条属性: csharp-winform/15-scrollbars.md
    - 16.时钟控件属性: csharp-winform/16-clocks.md
    - 17.时钟控件tick事件: csharp-winform/17-clock-events.md
    - 18.分组框属性: csharp-winform/18-groupboxes.md
    - 19.选项卡属性: csharp-winform/19-tabcontrols.md
    - 20.多文件界面窗体: csharp-winform/20-mdi-forms.md
    - 21.多窗体的调用: csharp-winform/21-multiple-forms.md
    - 22.常见控件用法: csharp-winform/22-common-controls.md
  - MySQL:
    - 考试大纲: mysql/index.md
    - 相关术语: mysql/terms.md
    - ===新人起步===:
      - 数据库简介: mysql/0-get-started/01-what-is-database.md
      - MySQL简介: mysql/0-get-started/02-what-is-mysql.md
      - MySQL语言组成: mysql/0-get-started/03-what-is-mysql-language.md
      - 安装与启动MySQL: mysql/0-get-started/04-installation.md
      - 登录与退出MySQL: mysql/0-get-started/05-login-logout.md
      - 大小写敏感性: mysql/0-get-started/06-case-sensitivity.md
      - 注释: mysql/0-get-started/07-comments.md
      - 标识符: mysql/0-get-startstarted/08-identifiers.md
      - 关键词: mysql/0-get-started/09-keywords.md
    - ===数据定义语言(DDL)===:
      - DDL简介: mysql/1-ddl/00-introduction.md
      - 查看数据库: mysql/1-ddl/01-show-databases.md
      - 创建数据库: mysql/1-ddl/02-create-database.md
      - 删除数据库: mysql/1-ddl/03-drop-database.md
      - 使用数据库: mysql/1-ddl/04-use-database.md
      - 修改数据库名: mysql/1-ddl/05-alter-database.md
      - 创建表: mysql/1-ddl/01-create-table.md
      - 查看表: mysql/1-ddl/02-show-table.md
      - 复制表: mysql/1-ddl/03-copy-table.md
      - 删除表: mysql/1-ddl/04-drop-table.md
      - 修改表: mysql/1-ddl/05-alter-table.md
      - 索引: mysql/1-ddl/06-index.md
      - 视图: mysql/1-ddl/07-view.md
      - 约束条件: mysql/1-ddl/constraints.md
    - ===数据操作语言(DML)===:
      - DML简介: mysql/2-dml/00-introduction.md
      - 插入数据: mysql/2-dml/01-insert-data.md
      - 删除数据: mysql/2-dml/02-delete-data.md
      - 更新数据: mysql/2-dml/03-update-data.md
      - 复制数据: mysql/2-dml/04-duplicate.md
    - ===数据类型===:
      - 数据类型概述: mysql/3-data-types/0-what-is-datatype.md
      - 整数类型: mysql/3-data-types/1-integer.md
      - 小数类型: mysql/3-data-types/2-decimal.md
      - 字符串类型: mysql/3-data-types/3-string.md
      - 布尔类型: mysql/3-data-types/4-boolean.md
      - 日期和时间类型: mysql/3-data-types/5-datetime.md
    - ===数据查询语言(DQL)===:
      - DQL简介: mysql/4-dql/00-introduction.md
      - SELECT语句: mysql/4-dql/1-select-statement.md
      - SELECT子句: mysql/4-dql/2-select.md
      - FROM子句: mysql/4-dql/3-from.md
      - WHERE子句: mysql/4-dql/4-where.md
      - GROUP BY子句: mysql/4-dql/5-group-by.md
      - HAVING子句: mysql/4-dql/6-having.md
      - ORDER BY子句: mysql/4-dql/7-order-by.md
      - LIMIT子句: mysql/4-dql/8-limit.md
      - 高级:多表连接查询: mysql/4-dql/9-join.md
      - 高级:子查询: mysql/4-dql/10-subquery.md
      - 高级:联合查询: mysql/4-dql/11-union.md
    - ===运算符===:
      - 运算符是什么: mysql/5-operators/01-what-is-operator.md
      - 算术运算符: mysql/5-operators/02-arithmetic.md
      - 关系运算符: mysql/5-operators/03-relational.md
      - 逻辑运算符: mysql/5-operators/04-logical.md
      - 位运算符: mysql/5-operators/05-bitwise.md
    - ===函数库===:
      - 字符串函数: mysql/6-function/string.md
      - 数学函数: mysql/6-function/math.md
      - 聚合函数: mysql/6-function/aggregate.md
      - 日期函数: mysql/6-function/date.md
      - 其他函数: mysql/6-function/others.md
    - ===控制结构===:
      - IF语句: mysql/7-control-structures/if.md
      - CASE语句: mysql/7-control-structures/case.md
      - 循环结构: mysql/7-control-structures/loop.md
    - ===其他===:
      - 数据库备份: mysql/10-others/backup.md
      - 创建用户: mysql/10-others/create-user.md
  - Office:
    - 考试大纲: office/index.md
    - Word:
      - 题库: office/word/exercises.md
      - Word的基本概念: office/word/01.md
      - 文档的基本操作: office/word/02.md
      - 文档的编辑与格式设置: office/word/03.md
      - 文档的段落与列表: office/word/04.md
      - 文档的表格与图形: office/word/05.md
      - 文档的页眉页脚与页码: office/word/06.md
      - 文档的打印与保存: office/word/07.md
    - Excel:
      - 题库: office/excel/exercises.md
      - Excel的基本概念: office/excel/01.md
      - 工作簿的基本操作: office/excel/02.md
      - 工作表的基本操作: office/excel/03.md
      - 单元格的基本操作: office/excel/04.md
      - 公式与函数: office/excel/05.md
      - 使用图表: office/excel/06.md
      - 数据清单管理: office/excel/07.md
      - 页面设置与打印: office/excel/08.md
    - PowerPoint:
      - 题库: office/powerpoint/exercises.md
      - PowerPoint的基本概念: office/powerpoint/1.md
      - 幻灯片的基本操作: office/powerpoint/2.md
      - 幻灯片的编辑与格式设置: office/powerpoint/3.md
      - 幻灯片的动画与切换: office/powerpoint/4.md
      - 幻灯片的放映与打印: office/powerpoint/5.md
      - 幻灯片的设计与布局: office/powerpoint/6.md
      - 幻灯片的多媒体与超链接: office/powerpoint/7.md
  - 计算机基础:
    - 考试大纲: computer-basics/index.md
    - 计算机进制: computer-basics/number-system.md
    - 计算机的组成: computer-basics/02-computer-structure.md
    - 操作系统: computer-basics/03-operating-system.md
    - Windows操作系统: computer-basics/04-windows-os.md
    - Linux操作系统: computer-basics/05-linux-os.md
    - 网络基础: computer-basics/06-network-basics.md
    - 网络协议: computer-basics/07-network-protocols.md
    - 网络设备: computer-basics/08-network-devices.md
  - Windows:
    - 考试大纲: windows10/index.md
    - 操作系统基础: windows10/01.md
    - Windows10基础: windows10/02.md
    - Windows10个性化设置: windows10/03.md
    - Windows10文件和文件夹管理1: windows10/04.md
    - Windows10文件和文件夹管理2: windows10/05.md
    - Windows10控制面板: windows10/06.md
    - Windows10任务管理器: windows10/07.md
    - Windows10实用工具: windows10/08.md
    - Windows10磁盘管理: windows10/09.md
    - Windows10中文输入: windows10/10.md
    - Windows10练习题: windows10/11.md
  - 计算机网络:
    - 考试大纲: computer-network-basics/index.md
  - 暑期作业:
    - 6月21日:For循环笔记: exercises/csharp-summer/0621.md
    - 6月22日:For循环练习: exercises/csharp-summer/0622.md
    - 6月23日:变量与常量: exercises/csharp-summer/0623-variables.md
    - 6月24日:while循环: exercises/csharp-summer/0624-while-loop.md
    - 6月25日:算数运算符: exercises/csharp-summer/0625.md
    - 6月26日:练习(41道): exercises/csharp-summer/0626.md
    - 6月27日:练习(16道): exercises/csharp-summer/0627.md
    - 6月28日:练习(18道): exercises/csharp-summer/0628.md
    - 6月29日:IF练习(40道): exercises/csharp-summer/0629.md
    - 6月30日:SWITCH练习(10道): exercises/csharp-summer/0630.md
    - 7月01日:三目运算符练习(10道): exercises/csharp-summer/0701.md
    - 7月02日:读书笔记1: exercises/csharp-summer/0702.md
    - 7月03日:读书笔记2: exercises/csharp-summer/0703.md
    - 7月04日:读书笔记3: exercises/csharp-summer/0704.md
    - 7月05日:读书笔记4: exercises/csharp-summer/0705.md
    - 7月06日:第5章类的基本概念: exercises/csharp-summer/0706.md
    - 7月07日:类练习题: exercises/csharp-summer/0707.md
    - 7月08日:类练习: exercises/csharp-summer/0708.md
    - 7月15日:计算机基础知识1: exercises/computer-basics/0715.md
    - 7月16日:计算机基础知识2: exercises/computer-basics/0716.md
    - 7月17日:计算机基础知识3: exercises/computer-basics/0717.md
    - 7月18日:操作系统概述: exercises/windows/0718.md
    - 7月19日:Win10基础: exercises/windows/0719.md
    - 7月20日:个性化设置: exercises/windows/0720.md
    - 7月21日:文件和文件夹管理1: exercises/windows/0721.md
    - 7月22日:文件和文件夹管理2: exercises/windows/0722.md
    - 7月23日控制面板: exercises/windows/0723.md
    - 7月24日任务管理器实用工具: exercises/windows/0724.md
    - 7月25日磁盘管理中文输入: exercises/windows/0725.md
    - 7月26日练习题: exercises/windows/0726.md
    - 8月7日MySQL建表: exercises/mysql/0807.md
    - 8月8日MySQL查询: exercises/mysql/0808.md
    - 8月9日ALTER TABLE: exercises/mysql/0809.md
    - 8月10日嵌套查询: exercises/mysql/0810.md
    - 8月11日算数运算符查询: exercises/mysql/0811.md
  - 作业库:
    - ===MySQL===:
      - 第一周建表: exercises/mysql/level1.md
      - 第二周查询: exercises/mysql/level2.md
      - 项目-查询学生成绩表: exercises/mysql/project1.md
      - 项目-查询产品信息表: exercises/mysql/project2.md
      - 项目-查询员工信息表: exercises/mysql/project3.md
      - 项目-查询随机信息表: exercises/mysql/project1-rand.md
      - 项目-查询打折价格表: exercises/mysql/project2-discount.md
      - 项目-农产品信息查询: exercises/mysql/project6-agriculture-product-price.md
      - 数据: exercises/mysql/data.md
  - 编程英语:
      - 首页: english/index.md
      - A: english/a.md
      - B: english/b.md
      - C: english/c.md
      - D: english/d.md
      - E: english/e.md
      - F: english/f.md
      - G: english/g.md
      - H: english/h.md
      - I: english/i.md
      - J: english/j.md
      - K: english/k.md
      - L: english/l.md
      - M: english/m.md
      - N: english/n.md
      - O: english/o.md
      - P: english/p.md
      - Q: english/q.md
      - R: english/r.md
      - S: english/s.md
      - T: english/t.md
      - U: english/u.md
      - V: english/v.md
      - W: english/w.md
      - X: english/x.md
      - Y: english/y.md
      - Z: english/z.md     