# Basic information
site_name: 2026年对口高考(计算机)V1.0
site_url: https://buhaoqi.github.io
site_author: 村长
site_description: >-
  2026年河北省中职对口升学考试计算机类专业考试学习交流。

# Copyright
copyright: Copyright &copy; 2023 - 2025 村长 <a href="https://beian.mps.gov.cn/#/query/webSearch?code=13040202001048" target="_blank">冀公网安备13040202001048号</a><a href="https://beian.miit.gov.cn/#/Integrated/index" target="_blank">冀ICP备2025101972号-1</a>
    

# Configuration
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    # - navigation.prune
    # - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    # - toc.follow
    - content.code.copy
    - content.code.select
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  # - blog:
    # - blog_dir: /blog/
  #- minify:
      #minify_html: true
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
# Page tree
nav:
  - 首页: 
    - 考试大纲: ./index.md
  - 算法与程序设计:
    - 考试大纲: csharp/textbook/index.md
    - 教材目录: csharp/textbook/cover.md
    - ===第1章.算法与程序基础===: 
      - 算法的定义及特性: csharp/textbook/1/algorithm-definition-and-characteristics.md
      - 算法描述与设计: csharp/textbook/1/algorithm-description-and-design.md
      - 算法分析和评价: csharp/textbook/1/algorithm-analysis-and-evaluation.md
      - 算法与程序的关系: csharp/textbook/1/algorithm-and-program-relationship.md
      - 典型算法举例: csharp/textbook/1/typical-algorithm-examples.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-1.md
        - 练习册实验: csharp/exams/trainning/2-1.md
        - 学海领航: csharp/exams/leading/1.md
        - 周测: csharp/exams/week-test/1.md
    - ===第2章.C#概述===: 
      - C#语言简介: csharp/textbook/2/csharp-overview.md
      - Visual Studio开发环境: csharp/textbook/2/visual-studio.md
      - 简单C#程序实例: csharp/textbook/2/simple-csharp-program.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-2.md
        - 练习册实验: csharp/exams/trainning/2-2.md
        - 学海领航: csharp/exams/leading/2.md
        - 周测: csharp/exams/week-test/2.md
    - ===第3章.C#语言基础===: 
      - 数据类型: csharp/textbook/3/data-types.md
      - 常量与变量: csharp/textbook/3/constants-and-variables.md
      - 运算符与表达式: csharp/textbook/3/operators-and-expressions.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-3.md
        - 练习册实验: csharp/exams/trainning/2-3.md
        - 学海领航: csharp/exams/leading/3.md
        - 周测3-3: csharp/exams/week-test/3-3.md
        - 周测3-4: csharp/exams/week-test/3-4.md
    - ===第4章.C#控制结构===: 
      - 顺序结构语句: csharp/textbook/4/flow-control.md
      - 分支结构语句: csharp/textbook/4/branching.md
      - 循环结构语句: csharp/textbook/4/looping.md
      - 跳转语句: csharp/textbook/4/jumping.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-4.md
        - 练习册实验: csharp/exams/trainning/2-4.md
        - 学海领航: csharp/exams/leading/4.md
        - 周测4-5: csharp/exams/week-test/4-5.md
        - 周测4-6: csharp/exams/week-test/4-6.md
        - 周测4-7: csharp/exams/week-test/4-7.md
    - ===第5章.Win应用程序开发===: 
      - 窗体设计: csharp/textbook/5/1-windows-application-design.md
      - 常用控件: csharp/textbook/5/2-common-controls.md
      - 对话框: csharp/textbook/5/3-dialogs.md
      - 文档程序设计: csharp/textbook/5/4-document-program-design.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-5.md
        - 练习册实验: csharp/exams/trainning/2-5.md
        - 学海领航: csharp/exams/leading/5.md
        - 周测5-8: csharp/exams/week-test/5-8.md
    - ===第6章.数组===: 
      - 一维数组: csharp/textbook/6/1-dimensional-arrays.md
      - 多维数组: csharp/textbook/6/2-multi-dimensional-arrays.md
      - 数组的遍历: csharp/textbook/6/3-array-traversal.md
      - 数组的排序和查找: csharp/textbook/6/4-array-sorting-and-searching.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-6.md
        - 练习册实验: csharp/exams/trainning/2-6.md
        - 学海领航: csharp/exams/leading/6.md
        - 周测6-9: csharp/exams/week-test/6-9.md
        - 周测6-10: csharp/exams/week-test/6-10.md
        - 周测6-11: csharp/exams/week-test/6-11.md
        - 周测6-12: csharp/exams/week-test/6-12.md
    - ===第7章.C#面向对象基础===: 
      - 类: csharp/textbook/7/class.md
      - 方法: csharp/textbook/7/methods.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-7.md
        - 练习册实验: csharp/exams/trainning/2-7.md
        - 学海领航: csharp/exams/leading/7.md
        - 周测7-13: csharp/exams/week-test/7-13.md
        - 周测7-14: csharp/exams/week-test/7-14.md
        - 周测7-15: csharp/exams/week-test/7-15.md
        - 周测7-16: csharp/exams/week-test/7-16.md
    - ===第8章.C#面向对象编程===: 
      - 类的封装与继承: csharp/textbook/8/class-encapsulation-and-inheritance.md
      - 多态: csharp/textbook/8/polymorphism.md
      - 接口: csharp/textbook/8/interfaces.md
      - 委托: csharp/textbook/8/delegates.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-8.md
        - 练习册实验: csharp/exams/trainning/2-8.md
        - 学海领航: csharp/exams/leading/8.md
        - 周测8-17: csharp/exams/week-test/8-17.md
        - 周测8-18: csharp/exams/week-test/8-18.md
        - 周测8-19: csharp/exams/week-test/8-19.md
        - 周测8-20: csharp/exams/week-test/8-20.md
    - ===第9章.C#常用类===: 
      - Math类: csharp/textbook/9/math-class.md
      - String类: csharp/textbook/9/string-class.md
      - DateTime类: csharp/textbook/9/datetime-class.md
      - Random类: csharp/textbook/9/random-class.md
      - Convert类: csharp/textbook/9/convert-class.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-9.md
        - 练习册实验: csharp/exams/trainning/2-9.md
        - 学海领航: csharp/exams/leading/9.md
        - 周测9-21: csharp/exams/week-test/9-21.md
        - 周测9-22: csharp/exams/week-test/9-22.md
        - 周测9-23: csharp/exams/week-test/9-23.md
    - ===第10章.C#文件操作===: 
      - 文件的种类: csharp/textbook/10/file-types.md
      - 创建文件: csharp/textbook/10/create-file.md
      - 读写文件: csharp/textbook/10/read-write-file.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-10.md
        - 练习册实验: csharp/exams/trainning/2-10.md
        - 学海领航: csharp/exams/leading/10.md
        - 周测10-24: csharp/exams/week-test/10-24.md
        - 周测10-25: csharp/exams/week-test/10-25.md
        - 周测10-26: csharp/exams/week-test/10-26.md
    - ===第11章.C#图形操作===: 
      - 图形设计基础: csharp/textbook/11/graphics-design-basics.md
      - 绘图工具及使用: csharp/textbook/11/graphics-tools-and-usage.md
      - 字体和图像处理: csharp/textbook/11/font-and-image-processing.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-11.md
        - 练习册实验: csharp/exams/trainning/2-11.md
        - 学海领航: csharp/exams/leading/11.md
        - 周测11-27: csharp/exams/week-test/11-27.md
    - ===第12章.数据库应用===: 
      - Connection连接字符串: csharp/textbook/12/connection-strings.md
      - 使用connection对象: csharp/textbook/12/using-connection.md
      - 连接的测试: csharp/textbook/12/connection-testing.md
      - 章节测试:
        - 练习册:  csharp/exams/trainning/1-12.md
        - 练习册实验: csharp/exams/trainning/2-12.md
        - 学海领航: csharp/exams/leading/12.md
        - 周测12-28: csharp/exams/week-test/12-28.md
        - 周测12-29: csharp/exams/week-test/12-29.md
    - ===综合模拟试卷===:
      - 练习册项目: csharp/exams/trainning/3-1.md
      - 练习册模拟试卷:
        - 练习册基础模拟1: csharp/exams/trainning/3-2.md
        - 练习册基础模拟2: csharp/exams/trainning/3-3.md
        - 练习册进阶模拟1: csharp/exams/trainning/3-4.md
        - 练习册进阶模拟2: csharp/exams/trainning/3-5.md
        - 练习册进阶模拟3: csharp/exams/trainning/3-6.md
      - 月考模拟试卷:
        - 月考模拟1: csharp/exams/week-test/month1.md
        - 月考模拟2: csharp/exams/week-test/month2.md
        - 月考模拟3: csharp/exams/week-test/month3.md
        - 月考模拟4: csharp/exams/week-test/month4.md
        - 月考模拟5: csharp/exams/week-test/month5.md
        - 月考模拟6: csharp/exams/week-test/month6.md
        - 月考模拟7: csharp/exams/week-test/month7.md
        - 月考模拟8: csharp/exams/week-test/month8.md
    - ===参考答案===:
      - 教材答案:
        - 项目1-2: csharp/textbook/answers/xm1.md
        - 项目3: csharp/textbook/answers/xm3.md
        - 项目4: csharp/textbook/answers/xm4.md
        - 项目5: csharp/textbook/answers/xm5.md
        - 项目6: csharp/textbook/answers/xm6.md
        - 项目7: csharp/textbook/answers/xm7.md
        - 项目8: csharp/textbook/answers/xm8.md
        - 项目9: csharp/textbook/answers/xm9.md
        - 项目10: csharp/textbook/answers/xm10.md
        - 项目11: csharp/textbook/answers/xm11.md
        - 项目12: csharp/textbook/answers/xm12.md
      - 练习册答案:
        - 练习册答案: csharp/exams/trainning/answer1.md
        - 练习册实验答案: csharp/exams/trainning/answer2.md
        - 练习册模拟答案: csharp/exams/trainning/answer3.md
      - 学海领航答案: csharp/exams/leading/answer.md
      - 周测月考答案: csharp/exams/week-test/answer-unit.md
  - 数据库原理与应用技术:
    - 考试大纲: mysql/textbook/index.md
    - 教材目录: mysql/textbook/cover.md
    - ===1.绪论===:
      - 数据库系统概述: mysql/textbook/1-database-basics/01-overview.md
      - 数据模型: mysql/textbook/1-database-basics/02-data-model.md
      - 数据库系统的结构: mysql/textbook/1-database-basics/03-database-system-architecture.md
    - ===2.MySQL工具使用===:
      - MySQL概述: mysql/textbook/2-mysql-install/01-what-is-mysql.md
      - MySQL的安装与配置: mysql/textbook/2-mysql-install/02-mysql-installation.md
      - MySQL服务的启动与停止: mysql/textbook/2-mysql-install/03-mysql-service-management.md
      - MySQL服务器的登录: mysql/textbook/2-mysql-install/04-login-logout.md
    - ===3.结构化查询语言(SQL)===:
      - SQL概述: mysql/textbook/3-mysql-basics/1-what-is-sql.md
      - SQL产生与发展: mysql/textbook/3-mysql-basics/2-sql-history.md
      - SQL的特点: mysql/textbook/3-mysql-basics/3-sql-features.md
    - ===3.MySQL数据类型===:
      - 数据类型简介: mysql/textbook/3-data-types/0-what-is-datatype.md
      - 整数类型: mysql/textbook/3-data-types/1-integer.md
      - 小数类型: mysql/textbook/3-data-types/2-decimal.md
      - 日期时间类型: mysql/textbook/3-data-types/3-datetime.md
      - 字符串类型: mysql/textbook/3-data-types/4-string.md
    - ===3.MySQL运算符===:
      - 算术运算符: mysql/textbook/3-operators/02-arithmetic.md
      - 比较运算符: mysql/textbook/3-operators/03-relational.md
      - 逻辑运算符: mysql/textbook/3-operators/04-logical.md
      - 位运算符: mysql/textbook/3-operators/05-bitwise.md
      - 运算符的优先级: mysql/textbook/3-operators/06-operator-precedence.md
    - ===3.MySQL函数===:
      - 聚合函数: mysql/textbook/3-function/2-aggregate.md
      - 数学函数: mysql/textbook/3-function/3-math.md
      - 字符串函数: mysql/textbook/3-function/4-string.md
      - 日期和时间函数: mysql/textbook/3-function/5-date.md
      - 系统信息函数: mysql/textbook/3-function/6-system-info.md
      - 其他函数: mysql/textbook/3-function/7-others.md
    - ===4.MySQL数据库管理===:
      - 创建数据库: mysql/textbook/4-ddl/02-create-database.md
      - 查看数据库: mysql/textbook/4-ddl/01-show-databases.md
      - 使用数据库: mysql/textbook/4-ddl/04-use-database.md
      - 修改数据库: mysql/textbook/4-ddl/05-alter-database.md
      - 删除数据库: mysql/textbook/4-ddl/03-drop-database.md
    - ===5.MySQL数据表管理===:
      - 创建数据表: mysql/textbook/5-ddl/01-create-table.md
      - 查看数据表结构: mysql/textbook/5-ddl/02-show-table.md
      - 修改数据表结构: mysql/textbook/5-ddl/05-alter-table.md
      - 重命名数据表: mysql/textbook/5-ddl/03-copy-table.md
      - 复制数据表: mysql/textbook/5-ddl/04-drop-table.md
      - 删除数据表: mysql/textbook/5-ddl/04-drop-table.md
    - ===6.MySQL数据完整性===:
      - 实体完整性: mysql/textbook/6-ddl/constraints.md
      - 参照完整性: mysql/textbook/6-ddl/referential-integrity.md
      - 用户定义完整性: mysql/textbook/6-ddl/user-defined-integrity.md
      - 完整性约束命名子句: mysql/textbook/6-ddl/integrity-constraints-naming.md
    - ===7.MySQL数据查询与更新===:
      - 表单查询: mysql/textbook/7-dml/1-form-query.md
      - 连接查询: mysql/textbook/7-dml/2-join.md
      - 嵌套查询: mysql/textbook/7-dml/3-subquery.md
      - 插入数据: mysql/textbook/7-dml/4-insert.md
      - 修改数据: mysql/textbook/7-dml/5-update.md
      - 删除数据: mysql/textbook/7-dml/6-delete.md
    - ===8.MySQL索引与视图===:
      - 索引: mysql/textbook/8-index-and-view/index.md
      - 视图: mysql/textbook/8-index-and-view/view.md
    - ===9.MySQL数据库编程===:
      - 触发器: mysql/textbook/9-database-programming/02-python-connection.md
      - 事件: mysql/textbook/9-database-programming/03-java-connection.md
      - 存储过程: mysql/textbook/9-database-programming/03-java-connection.md
      - 存储函数: mysql/textbook/9-database-programming/03-java-connection.md
    - ===10.数据库设计===:
      - 需求分析: mysql/textbook/10-database-design/01-requirements-analysis.md
      - 概念结构设计: mysql/textbook/10-database-design/02-conceptual-design.md
      - 逻辑结构设计: mysql/textbook/10-database-design/03-logical-design.md
      - 物理结构设计: mysql/textbook/10-database-design/04-physical-design.md
      - 数据库的实施和维护: mysql/textbook/10-database-design/04-physical-design.md
      - 关系模式的规范化: mysql/textbook/10-database-design/04-physical-design.md
    - ===11.数据库安全===:
      - 数据库安全概述: mysql/textbook/11-database-security/01-overview.md
      - 用户管理: mysql/textbook/11-database-security/02-user-management.md
      - 权限管理: mysql/textbook/11-database-security/03-privilege-management.md
      - 角色管理: mysql/textbook/11-database-security/04-role-management.md
    - ===12.数据库备份和恢复===:
      - 数据库备份概述: mysql/textbook/12-database-backup/01-overview.md
      - 使用MySQLDUMP进行备份: mysql/textbook/12-database-backup/02-mysqldump.md
      - MySQL数据恢复: mysql/textbook/12-database-backup/03-data-recovery.md
  - 计算机网络基础:
    - 考试大纲: network-basics/index.md
    - 教材目录: network-basics/contents.md
    - ===1.计算机网络概述===:
      - 计算机网络的发展: network-basics/1/01-development.md
      - 计算机网络的基本概念: network-basics/1/02-basics.md
      - 计算机网络的分类: network-basics/1/03-classification.md
      - 计算机网络的组成: network-basics/1/04-architecture.md
      - 计算机网络拓扑结构: network-basics/1/05-topology.md
      - 计算机网络的功能和应用: network-basics/1/06-functions-and-applications.md
      - 计算机网络传输介质: network-basics/1/07-transmission-media.md
      - 网络技术的新发展: network-basics/1/08-new-developments.md
    - ===2.数据通信基础===:
      - 数据通信系统概述: network-basics/2/01-overview.md
      - 通信的基本方式: network-basics/2/02-methods.md
      - 通信中的编码技术: network-basics/2/03-encoding.md
      - 同步技术与多路复用: network-basics/2/04-synchronization-and-multiplexing.md
      - 数据交换技术: network-basics/2/05-exchange.md
      - 差错控制技术: network-basics/2/06-error-control.md
    - ===3.OSI参考模型体系===:
      - 网络标准化组织: network-basics/3/01-standards-organization.md
  - 中文版OFFICE实用教程:
    - 考试大纲: office/index.md
    - Word:
      - 题库: office/word/exercises.md
      - Word的基本概念: office/word/01.md
      - 文档的基本操作: office/word/02.md
      - 文档的编辑与格式设置: office/word/03.md
      - 文档的段落与列表: office/word/04.md
      - 文档的表格与图形: office/word/05.md
      - 文档的页眉页脚与页码: office/word/06.md
      - 文档的打印与保存: office/word/07.md
    - Excel:
      - 题库: office/excel/exercises.md
      - Excel的基本概念: office/excel/01.md
      - 工作簿的基本操作: office/excel/02.md
      - 工作表的基本操作: office/excel/03.md
      - 单元格的基本操作: office/excel/04.md
      - 公式与函数: office/excel/05.md
      - 使用图表: office/excel/06.md
      - 数据清单管理: office/excel/07.md
      - 页面设置与打印: office/excel/08.md
    - PowerPoint:
      - 题库: office/powerpoint/exercises.md
      - PowerPoint的基本概念: office/powerpoint/1.md
      - 幻灯片的基本操作: office/powerpoint/2.md
      - 幻灯片的编辑与格式设置: office/powerpoint/3.md
      - 幻灯片的动画与切换: office/powerpoint/4.md
      - 幻灯片的放映与打印: office/powerpoint/5.md
      - 幻灯片的设计与布局: office/powerpoint/6.md
      - 幻灯片的多媒体与超链接: office/powerpoint/7.md
  - 计算机基础及应用:
    - 考试大纲: computer-basics/index.md
    - 计算机进制: computer-basics/number-system.md
    - 计算机的组成: computer-basics/02-computer-structure.md
    - 操作系统: computer-basics/03-operating-system.md
    - Windows操作系统: computer-basics/04-windows-os.md
    - Linux操作系统: computer-basics/05-linux-os.md
    - 网络基础: computer-basics/06-network-basics.md
    - 网络协议: computer-basics/07-network-protocols.md
    - 网络设备: computer-basics/08-network-devices.md
    - 考试大纲: windows10/index.md
    - 操作系统基础: windows10/01.md
    - Windows10基础: windows10/02.md
    - Windows10个性化设置: windows10/03.md
    - Windows10文件和文件夹管理1: windows10/04.md
    - Windows10文件和文件夹管理2: windows10/05.md
    - Windows10控制面板: windows10/06.md
    - Windows10任务管理器: windows10/07.md
    - Windows10实用工具: windows10/08.md
    - Windows10磁盘管理: windows10/09.md
    - Windows10中文输入: windows10/10.md
    - Windows10练习题: windows10/11.md
    