// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  // ============ C#侧边栏 ============
  csharpSidebar: [
    {
      type: 'doc',
      id: 'csharp/intro',  // 确保 docs/csharp/intro.md 存在
      label: '考试大纲',
    },
    // 项目一：算法与程序基础（一级分类）
    {
      type: 'category',
      label: '项目一 算法与程序基础', // 分组标题
      collapsible: true, // 可折叠（默认true）
      collapsed: false, // 默认展开（根据需要改true为折叠）
      items: [
        // 任务一 
        {
          type: 'category',
          label: '任务一 算法的定义与特性',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task1/1', // 
            'csharp/ch01/task1/exercises', // 
          ],
        },
        // 任务二
        {
          type: 'category',
          label: '任务二 算法的描述与设计',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task2/1', // 
            'csharp/ch01/task2/2', // 
            'csharp/ch01/task2/3', // 
            'csharp/ch01/task2/exercises', // 
          ],
        },
        // 任务三
        {
          type: 'category',
          label: '任务三 算法分析与评价',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task3/1', // 
            'csharp/ch01/task3/2', //  
          ],
        },
        'csharp/ch01/task4', // 任务四 算法与程序的关系
        // 任务
        {
          type: 'category',
          label: '任务五 典型算法举例',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task5/1', // 
            'csharp/ch01/task5/2', // 
            'csharp/ch01/task5/3', // 
          ],
        }
      ],
    },

    // 项目二：C#概述（一级分类）
    {
      type: 'category',
      label: '项目二 C#概述',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch02/overview', // 概述
        'csharp/ch02/task1', // 任务一
        'csharp/ch02/task2', // 任务二 
        'csharp/ch02/task3', // 任务三 
      ],
    },

    // 项目三：C#语言基础（一级分类，包含带子项的任务 + 练习题）
    {
      type: 'category',
      label: '项目三 C#语言基础',
      collapsible: true,
      collapsed: false,
      items: [
        // 任务一 数据类型（二级分类，带子项，显示折叠箭头）
        {
          type: 'category',
          label: '任务一 数据类型',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch03/task1/overview', // 
            'csharp/ch03/task1/type-int', // 
            'csharp/ch03/task1/type-decimal', // 
            'csharp/ch03/task1/type-char', // 
            'csharp/ch03/task1/type-bool', // 
            'csharp/ch03/task1/type-struct', // 
            'csharp/ch03/task1/type-enum', // 
            'csharp/ch03/task1/type-string', // 
            'csharp/ch03/task1/type-alias', // 
            'csharp/ch03/task1/implicit-convention', // 
            'csharp/ch03/task1/brace', // 
            'csharp/ch03/task1/parse', // 
            'csharp/ch03/task1/convert', // 
            'csharp/ch03/task1/type-object', // 
          ],
        },
        // 任务二 常量与变量（二级分类，带子项）
        {
          type: 'category',
          label: '任务二 常量与变量',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch03/task2/constant', // 常量
            'csharp/ch03/task2/variable', // 变量
          ],
        },
        // 任务三 运算符与表达式（二级分类，带子项）
        {
          type: 'category',
          label: '任务三 运算符与表达式',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch03/task3/overview', // 
            'csharp/ch03/task3/arithmetic-operators', // 
            'csharp/ch03/task3/increment-decrement-operators', // 
            'csharp/ch03/task3/assignment-operators', // 
            'csharp/ch03/task3/comparison-operators', // 
            'csharp/ch03/task3/logical-operators', // 
            'csharp/ch03/task3/conditional-operators', // 
            'csharp/ch03/task3/precedence-and-associativity', // 
          ],
        },
        'csharp/ch03/exercise', // 练习题（单独的文档项）
      ],
    },

    // 项目四：C#控制结构（一级分类）
    {
      type: 'category',
      label: '项目四 C#控制结构',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch04/overview', // 顺序结构基础
        // 任务一 顺序结构（二级分类，带子项）
        {
          type: 'category',
          label: '任务一 顺序结构语句',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task1/overview', // 
            'csharp/ch04/task1/console-writeline', // 
            'csharp/ch04/task1/console-write', // 
            'csharp/ch04/task1/console-readline', // 
            'csharp/ch04/task1/console-read', // 
            'csharp/ch04/task1/console-readkey', // 
          ],
        },
        // 任务二 分支结构（二级分类，带子项）
        {
          type: 'category',
          label: '任务二 分支结构',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task2/overview', // 
            'csharp/ch04/task2/if-statement', // if语句
            'csharp/ch04/task2/switch-statement', // switch语句
          ],
        },
        // 任务三 循环结构（二级分类，带子项）
        {
          type: 'category',
          label: '任务三 循环结构',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task3/loop-for', // for循环
            'csharp/ch04/task3/loop-while', // while循环
          ],
        },
        // 任务四 跳转语句（二级分类，带子项）
        {
          type: 'category',
          label: '任务四 跳转语句',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task4/break-statement', // break语句
            'csharp/ch04/task4/continue-statement', // continue语句
          ],
        },
        'csharp/ch04/exercise', // 练习题（单独的文档项）
      ],
    },

    // 项目五：窗体应用程序开发
    {
      type: 'category',
      label: '项目五 窗体应用程序开发',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch05/overview', // 概述
        'csharp/ch05/task1', // 任务一 窗体设计
        'csharp/ch05/task2', // 任务二 常用控件
        'csharp/ch05/task3', // 任务三 对话框
        'csharp/ch05/task4', // 任务四 文档程序设计
      ],
    },
    // 项目六 数组
    {
      type: 'category',
      label: '项目六 数组',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch06/overview', // 概述
        'csharp/ch06/task1', // 任务一 一维数组
        'csharp/ch06/task2', // 任务二 多维数组
        'csharp/ch06/task3', // 任务三 数组的遍历
        'csharp/ch06/task4', // 任务四 数组的排序
        'csharp/ch06/task5', // 任务四 数组的查找
      ],
    },
  ],
  // ============ 新增的 MySQL 教程侧边栏 ============
  mysqlSidebar: [
    {
      type: 'doc',
      id: 'mysql/intro',  // 确保 docs/mysql/intro.md 存在
      label: '考试大纲',
    },
    {
      type: 'doc',
      id: 'mysql/data',  // 确保 docs/mysql/intro.md 存在
      label: '数据表',
    },
    // 项目一：绪论
    {
      type: 'category',
      label: '项目一 绪论',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch01/overview', // 概述
        'mysql/ch01/task1', // 任务一 数据库系统概述
        'mysql/ch01/task2', // 任务二 多维数组
        'mysql/ch01/task3', // 任务三 数组的遍历
      ],
    },
    // 项目二
    {
      type: 'category',
      label: '项目二 MySQL 工具使用',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch02/overview', // 概述
        'mysql/ch02/task1', // 任务一 
        'mysql/ch02/task2', // 任务二 
        'mysql/ch02/task3', // 任务三 
        'mysql/ch02/task4', // 任务四
      ],
    },
    // 项目三
    {
      type: 'category',
      label: '项目三 MySQL基础知识',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch03/overview', // 概述
        'mysql/ch03/task1', // 任务一 
        'mysql/ch03/task2', // 任务二 
        'mysql/ch03/task3', // 任务三
        'mysql/ch03/task4', // 任务四
        'mysql/ch03/demo1', // 案例 1
        'mysql/ch03/demo2', // 案例 2
      ],
    },
    // 项目四
    {
      type: 'category',
      label: '项目四 MySQL数据库管理',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch04/overview', // 概述
        'mysql/ch04/task1', // 任务一 
        'mysql/ch04/task2', // 任务二 
        'mysql/ch04/task3', // 任务三 
        'mysql/ch04/task4', // 任务三 
        'mysql/ch04/task5', // 任务三 
      ],
    },
    // 项目五
    {
      type: 'category',
      label: '项目五 MySQL数据表管理',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch05/overview', // 概述
        'mysql/ch05/task1', // 任务一 
        'mysql/ch05/task2', // 任务二 
        'mysql/ch05/task3', // 任务三 
        'mysql/ch05/task4', // 任务二 
        'mysql/ch05/task5', // 任务三 
        'mysql/ch05/task6', // 任务二 
      ],
    },
    // 项目六
    {
      type: 'category',
      label: '项目六 数据库完整性',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch06/overview', // 概述
        'mysql/ch06/task1', // 任务一 
        'mysql/ch06/task2', // 任务二 
        'mysql/ch06/task3', // 任务三
        'mysql/ch06/task4', // 任务四
        'mysql/ch06/demo1', // 案例 1
      ],
    },
    // 项目七
    {
      type: 'category',
      label: '项目七 数据查询与更新',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch07/overview', // 概述
        'mysql/ch07/task1', // 任务一 
        'mysql/ch07/task2', // 任务二 
        'mysql/ch07/task3', // 任务三 
        'mysql/ch07/task4', // 任务一 
        'mysql/ch07/task5', // 任务二 
        'mysql/ch07/task6', // 任务三 
        'mysql/ch07/demo1', // 案例 1
        'mysql/ch07/demo2', // 案例 2
      ],
    },
    // 项目八
    {
      type: 'category',
      label: '项目八  索引与视图',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch08/overview', // 概述
        'mysql/ch08/task1', // 任务一 
        'mysql/ch08/task2', // 任务二
        'mysql/ch08/exercise1', // 索引专项训练 
        'mysql/ch08/exercise2', // 视图专项训练
      ],
    },
    // 项目九
    {
      type: 'category',
      label: '项目九 数据库编程',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch09/overview', // 概述
        'mysql/ch09/task1', // 任务一 
        'mysql/ch09/task2', // 任务二 
        'mysql/ch09/task3', // 任务三
        'mysql/ch09/task4', // 任务三 
        'mysql/ch09/atta-variable', // 任务三 
        'mysql/ch09/exercise1', // 专项训练 
        'mysql/ch09/exercise2', // 专项训练 
        'mysql/ch09/exercise3', // 专项训练 
        'mysql/ch09/exercise4', // 专项训练 
      ],
    },
    // 项目十
    {
      type: 'category',
      label: '项目十 数据库设计',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch10/overview', // 概述
        'mysql/ch10/task1', // 任务一 
        'mysql/ch10/task2', // 任务二 
        'mysql/ch10/task3', // 任务三 
        'mysql/ch10/task4', // 任务一 
        'mysql/ch10/task5', // 任务二 
        'mysql/ch10/task6', // 任务三 
      ],
    },
    // 项目十一
    {
      type: 'category',
      label: '项目十一 数据库安全',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch11/overview', // 概述
        'mysql/ch11/task1', // 任务一 
        'mysql/ch11/task2', // 任务二 
        'mysql/ch11/task3', // 任务三 
      ],
    },
    // 项目十二
    {
      type: 'category',
      label: '项目十二 数据库备份和恢复',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch12/overview', // 概述
        'mysql/ch12/task1', // 任务一 
        'mysql/ch12/task2', // 任务二 
        'mysql/ch12/task3', // 任务三 
      ],
    }
  ],
};

export default sidebars;
