// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  // ============ C#侧边栏 ============
  csharpSidebar: [
    {
      type: 'doc',
      id: 'csharp/intro',  // 确保 docs/csharp/intro.md 存在
      label: '考试大纲',
    },
    // 项目一：算法与程序基础（一级分类）
    {
      type: 'category',
      label: '项目一 算法与程序基础', // 分组标题
      collapsible: true, // 可折叠（默认true）
      collapsed: false, // 默认展开（根据需要改true为折叠）
      items: [
        'csharp/ch01/overview', // 概述
        // 任务一 
        {
          type: 'category',
          label: '任务一 算法的定义与特性',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task1/1', // 
            'csharp/ch01/task1/exercises', // 
          ],
        },
        // 任务二
        {
          type: 'category',
          label: '任务二 算法的描述与设计',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task2/1', // 
            'csharp/ch01/task2/2', // 
            'csharp/ch01/task2/3', // 
            'csharp/ch01/task2/exercises', // 
          ],
        },
        // 任务三
        {
          type: 'category',
          label: '任务三 算法分析与评价',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task3/1', // 
            'csharp/ch01/task3/2', //  
          ],
        },
        'csharp/ch01/task4', // 任务四 算法与程序的关系
        // 任务
        {
          type: 'category',
          label: '任务五 典型算法举例',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch01/task5/1', // 
            'csharp/ch01/task5/2', // 
            'csharp/ch01/task5/3', // 
            'csharp/ch01/task5/4', // 
            'csharp/ch01/task5/5', // 
          ],
        }
      ],
    },

    // 项目二：C#概述（一级分类）
    {
      type: 'category',
      label: '项目二 C#概述',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch02/overview', // 概述
        'csharp/ch02/task1', // 任务一
        'csharp/ch02/task2', // 任务二 
        'csharp/ch02/task3', // 任务三 
      ],
    },

    // 项目三：C#语言基础（一级分类，包含带子项的任务 + 练习题）
    {
      type: 'category',
      label: '项目三 C#语言基础',
      collapsible: true,
      collapsed: false,
      items: [
        // 任务一 数据类型（二级分类，带子项，显示折叠箭头）
        {
          type: 'category',
          label: '任务一 数据类型',
          collapsible: true,
          collapsed: true, // 默认折叠（显示箭头）
          items: [
            'csharp/ch03/task1/overview', // 
            'csharp/ch03/task1/type-int', // 
            'csharp/ch03/task1/type-decimal', // 
            'csharp/ch03/task1/type-char', // 
            'csharp/ch03/task1/type-bool', // 
            'csharp/ch03/task1/type-struct', // 
            'csharp/ch03/task1/type-enum', // 
            'csharp/ch03/task1/type-string', // 
            'csharp/ch03/task1/type-tuple', // 
            'csharp/ch03/task1/type-alias', // 
            'csharp/ch03/task1/implicit-convention', // 
            'csharp/ch03/task1/brace', // 
            'csharp/ch03/task1/parse', // 
            'csharp/ch03/task1/convert', // 
            'csharp/ch03/task1/type-object', // 
          ],
        },
        // 任务二 常量与变量（二级分类，带子项）
        {
          type: 'category',
          label: '任务二 常量与变量',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch03/task2/constant', // 常量
            'csharp/ch03/task2/variable', // 变量
          ],
        },
        // 任务三 运算符与表达式（二级分类，带子项）
        {
          type: 'category',
          label: '任务三 运算符与表达式',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch03/task3/overview', // 
            'csharp/ch03/task3/arithmetic-operators', // 
            'csharp/ch03/task3/increment-decrement-operators', // 
            'csharp/ch03/task3/assignment-operators', // 
            'csharp/ch03/task3/comparison-operators', // 
            'csharp/ch03/task3/logical-operators', // 
            'csharp/ch03/task3/conditional-operators', // 
            'csharp/ch03/task3/precedence-and-associativity', // 
          ],
        },
        'csharp/ch03/exercise', // 练习题（单独的文档项）
      ],
    },

    // 项目四：C#控制结构（一级分类）
    {
      type: 'category',
      label: '项目四 C#控制结构',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch04/overview', // 顺序结构基础
        // 任务一 顺序结构（二级分类，带子项）
        {
          type: 'category',
          label: '任务一 顺序结构语句',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task1/overview', // 
            'csharp/ch04/task1/console-writeline', // 
            'csharp/ch04/task1/console-write', // 
            'csharp/ch04/task1/console-readline', // 
            'csharp/ch04/task1/console-read', // 
            'csharp/ch04/task1/console-readkey', // 
          ],
        },
        // 任务二 分支结构（二级分类，带子项）
        {
          type: 'category',
          label: '任务二 分支结构',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task2/overview', // 
            'csharp/ch04/task2/if-statement', // if语句
            'csharp/ch04/task2/switch-statement', // switch语句
          ],
        },
        // 任务三 循环结构（二级分类，带子项）
        {
          type: 'category',
          label: '任务三 循环结构',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task3/loop-for', // for循环
            'csharp/ch04/task3/exercise-for', // 练习题（单独的文档项）
            'csharp/ch04/task3/loop-while', // while循环
            'csharp/ch04/task3/exercise-while', // 练习题（单独的文档项）
          ],
        },
        // 任务四 跳转语句（二级分类，带子项）
        {
          type: 'category',
          label: '任务四 跳转语句',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch04/task4/break-statement', // break语句
            'csharp/ch04/task4/continue-statement', // continue语句
          ],
        },
      ],
    },

    // 项目五：窗体应用程序开发
    {
      type: 'category',
      label: '项目五 窗体应用程序开发',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch05/overview', // 概述
        'csharp/ch05/task1', // 任务一 窗体设计
        // 任务二 常用控件（二级分类，带子项）
        {
          type: 'category',
          label: '任务二 常用控件',
          collapsible: true,
          collapsed: true,
          items: [
            'csharp/ch05/task2/overview', // 
            'csharp/ch05/task2/label', // 
            'csharp/ch05/task2/textbox', //
            'csharp/ch05/task2/button', //
            'csharp/ch05/task2/combobox', //
            'csharp/ch05/task2/listbox', //
            'csharp/ch05/task2/radiobutton', //
            'csharp/ch05/task2/checkbox', //
            'csharp/ch05/task2/hscrollbar-vscrollbar', //
            'csharp/ch05/task2/timer', //
            'csharp/ch05/task2/groupbox', // 
            'csharp/ch05/task2/tabcontrol', // 
          ],
        },
        'csharp/ch05/task3', // 任务三 对话框
        'csharp/ch05/task4', // 任务四 文档程序设计
        'csharp/ch05/exercise1', // 任务四 文档程序设计
        'csharp/ch05/exercise2', // 任务四 文档程序设计
        'csharp/ch05/exercise3', // 任务四 文档程序设计
      ],
    },
    // 项目六 数组
    {
      type: 'category',
      label: '项目六 数组',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch06/overview', // 概述
        'csharp/ch06/task1', // 任务一 一维数组
        'csharp/ch06/task2', // 任务二 多维数组
        'csharp/ch06/task3', // 任务三 数组方法
        'csharp/ch06/task4', // 任务四 数组的排序
        'csharp/ch06/task5', // 任务五 同步实验
        'csharp/ch06/task6', // 任务六 同步训练
      ],
    },
    // 项目七 面向对象基础
    {
      type: 'category',
      label: '项目七 面向对象基础',
      collapsible: true,
      collapsed: false,
      items: [
          'csharp/ch07/class_basics/overview-class', // 概述
          'csharp/ch07/class_basics/class', // 任务一 
          'csharp/ch07/class_basics/modifiers', // 任务四 
          'csharp/ch07/class_basics/fields', // 任务二 
          'csharp/ch07/class_basics/property', // 任务五
          'csharp/ch07/class_basics/constructor', // 任务三 
          'csharp/ch07/class_basics/this', // 任务六
          'csharp/ch07/class_basics/static-class', // 任务六
          'csharp/ch07/class_basics/nested-class', // 任务六
          'csharp/ch07/method_basics/overview-method', // 概述
          'csharp/ch07/method_basics/what-method-is', // 任务一 
          'csharp/ch07/method_basics/parameters', // 任务二 
          'csharp/ch07/method_basics/reload', // 任务三 
          'csharp/ch07/exercise1', // 任务四
          'csharp/ch07/exercise2', // 任务五
        ],
    },
    // 项目八：面向对象编程
    {
      type: 'category',
      label: '项目八 面向对象编程',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch08/overview', // 概述
        'csharp/ch08/task1', // 任务一
        'csharp/ch08/task2', // 任务二 
        'csharp/ch08/task3', // 任务三 
        'csharp/ch08/task4', // 任务一
        'csharp/ch08/task5', // 任务二 
        'csharp/ch08/task6', // 任务三 
        'csharp/ch08/task7', // 任务一
      ],
    },
    // 项目九：C#常用类
    {
      type: 'category',
      label: '项目九 C#常用类',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch09/overview', // 概述
        'csharp/ch09/task1', // 任务一
        'csharp/ch09/task2', // 任务二 
        'csharp/ch09/task3', // 任务三 
        'csharp/ch09/task4', // 任务一
        'csharp/ch09/task5', // 任务二 
        'csharp/ch09/task6', // 任务三 
        'csharp/ch09/task7', // 任务一
      ],
    },
    // 项目示十：C#文件操作
    {
      type: 'category',
      label: '项目示十 C#文件操作',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch10/overview', // 概述
        'csharp/ch10/task1', // 任务一
        'csharp/ch10/task2', // 任务二 
        'csharp/ch10/task3', // 任务三 
        'csharp/ch10/task4', // 任务一
        'csharp/ch10/task5', // 任务二 
      ],
    },
    // 项目示十一：C#图形操作
    {
      type: 'category',
      label: '项目示十一 C#图形操作',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp/ch11/overview', // 概述
        'csharp/ch11/task1', // 任务一
        'csharp/ch11/task2', // 任务二 
      ],
    },
  ],
  // ============ 新增的 MySQL 教程侧边栏 ============
  csharpTutorials: [
     {
      type: 'doc',
      id: 'csharp-tutorials/index',  // 确保 docs/mysql/intro.md 存在
      label: '首页',
    },
    // 2026 年 3 月
    {
      type: 'category',
      label: '2026年 1 月',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp-tutorials/202601/0101', // 
        'csharp-tutorials/202601/0102', // 
        'csharp-tutorials/202601/0103', // 
        'csharp-tutorials/202601/0104', // 
        'csharp-tutorials/202601/0105', // 
        'csharp-tutorials/202601/0106', // 
        'csharp-tutorials/202601/0107', // 
        'csharp-tutorials/202601/0108', // 
        'csharp-tutorials/202601/0109', // 
        'csharp-tutorials/202601/0110', // 
        'csharp-tutorials/202601/0111', // 
        'csharp-tutorials/202601/0112', // 
        'csharp-tutorials/202601/0113', // 
        'csharp-tutorials/202601/0114', // 
        'csharp-tutorials/202601/0115', // 
        'csharp-tutorials/202601/0116', // 
        'csharp-tutorials/202601/0117', // 
        'csharp-tutorials/202601/0118', // 
        'csharp-tutorials/202601/0119', // 
        'csharp-tutorials/202601/0120', // 
      ],
    },
    // 2026 年 3 月
    {
      type: 'category',
      label: '2026年 2 月',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp-tutorials/202602/0201', // 
        'csharp-tutorials/202602/0202', // 
        'csharp-tutorials/202602/0203', // 
        'csharp-tutorials/202602/0204', // 
        'csharp-tutorials/202602/0205', // 
        'csharp-tutorials/202602/0206', // 
        'csharp-tutorials/202602/0207', // 
        'csharp-tutorials/202602/0208', // 
        'csharp-tutorials/202602/0209', // 
        'csharp-tutorials/202602/0210', // 
      ],
    },
    // 2026 年 3 月
    {
      type: 'category',
      label: '2026年 3 月',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp-tutorials/202603/0306', // 
        'csharp-tutorials/202603/0307', // 
        'csharp-tutorials/202603/0308', // 
        'csharp-tutorials/202603/0309', //
        'csharp-tutorials/202603/0310', //
        'csharp-tutorials/202603/0311', //
        'csharp-tutorials/202603/0312', //
        'csharp-tutorials/202603/0313', // 
        'csharp-tutorials/202603/0314', // 
        'csharp-tutorials/202603/0315', // 
        'csharp-tutorials/202603/0316', // 
        'csharp-tutorials/202603/0317', // 
        'csharp-tutorials/202603/0318', // 
        'csharp-tutorials/202603/0323', // 
        'csharp-tutorials/202603/0324', // 
        'csharp-tutorials/202603/0325', // 
        'csharp-tutorials/202603/0326', // 
        'csharp-tutorials/202603/0327', // 
        'csharp-tutorials/202603/0328', //
        'csharp-tutorials/202603/0329', // 
        'csharp-tutorials/202603/0330', // 
        'csharp-tutorials/202603/0331', // 
      ],
    },
    // 2026 年 4 月
    {
      type: 'category',
      label: '2026年 4 月',
      collapsible: true,
      collapsed: false,
      items: [
        'csharp-tutorials/202604/0401', // 
        'csharp-tutorials/202604/0402', // 
        'csharp-tutorials/202604/0403', // 
        'csharp-tutorials/202604/0404', // 
        'csharp-tutorials/202604/0405', // 
        'csharp-tutorials/202604/0406', // 
        'csharp-tutorials/202604/0407', // 
        'csharp-tutorials/202604/0408', // 
        'csharp-tutorials/202604/0409', // 
        'csharp-tutorials/202604/0410', // 
        'csharp-tutorials/202604/0411', // 
        'csharp-tutorials/202604/0412', // 
        'csharp-tutorials/202604/0413', // 
        'csharp-tutorials/202604/0414', // 
        'csharp-tutorials/202604/0415', // 
        'csharp-tutorials/202604/0416', // 
        'csharp-tutorials/202604/0417', // 
        'csharp-tutorials/202604/0418', // 
        'csharp-tutorials/202604/0423', // 
        'csharp-tutorials/202604/0424', // 
        'csharp-tutorials/202604/0425', // 
        'csharp-tutorials/202604/0426', // 
        'csharp-tutorials/202604/0427', // 
        'csharp-tutorials/202604/0428', //
        'csharp-tutorials/202604/0429', // 
        'csharp-tutorials/202604/0430', // 
      ],
    },
  ],
  // ============ 新增的 MySQL 教程侧边栏 ============
  mysqlSidebar: [
    {
      type: 'doc',
      id: 'mysql/intro',  // 确保 docs/mysql/intro.md 存在
      label: '考试大纲',
    },
     {
      type: 'doc',
      id: 'mysql/important',  // 确保 docs/mysql/intro.md 存在
      label: '重要概念',
    },
    {
      type: 'doc',
      id: 'mysql/data',  // 确保 docs/mysql/intro.md 存在
      label: '数据表',
    },
    // 项目一：绪论
    {
      type: 'category',
      label: '项目一 绪论',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch01/overview', // 概述
        'mysql/ch01/task1', // 任务一 数据库系统概述
        'mysql/ch01/task2', // 任务二 多维数组
        'mysql/ch01/task3', // 任务三 数组的遍历
      ],
    },
    // 项目二
    {
      type: 'category',
      label: '项目二 MySQL 工具使用',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch02/overview', // 概述
        'mysql/ch02/task1', // 任务一 
        'mysql/ch02/task2', // 任务二 
        'mysql/ch02/task3', // 任务三 
        'mysql/ch02/task4', // 任务四
      ],
    },
    // 项目三
    {
      type: 'category',
      label: '项目三 MySQL基础知识',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch03/overview', // 概述
        'mysql/ch03/task1', // 任务一 
        'mysql/ch03/task2', // 任务二 
        'mysql/ch03/task3', // 任务三
        'mysql/ch03/task4', // 任务四
        'mysql/ch03/demo1', // 案例 1
        'mysql/ch03/demo2', // 案例 2
      ],
    },
    // 项目四
    {
      type: 'category',
      label: '项目四 MySQL数据库管理',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch04/overview', // 概述
        'mysql/ch04/task1', // 任务一 
        'mysql/ch04/task2', // 任务二 
        'mysql/ch04/task3', // 任务三 
        'mysql/ch04/task4', // 任务三 
        'mysql/ch04/task5', // 任务三 
      ],
    },
    // 项目五
    {
      type: 'category',
      label: '项目五 MySQL数据表管理',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch05/overview', // 概述
        'mysql/ch05/task1', // 任务一 
        'mysql/ch05/task2', // 任务二 
        'mysql/ch05/task3', // 任务三 
        'mysql/ch05/task4', // 任务二 
        'mysql/ch05/task5', // 任务三 
        'mysql/ch05/task6', // 任务二 
      ],
    },
    // 项目六
    {
      type: 'category',
      label: '项目六 数据库完整性',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch06/overview', // 概述
        'mysql/ch06/task1', // 任务一 
        'mysql/ch06/task2', // 任务二 
        'mysql/ch06/task3', // 任务三
        'mysql/ch06/task4', // 任务四
        'mysql/ch06/demo1', // 案例 1
      ],
    },
    // 项目七
    {
      type: 'category',
      label: '项目七 数据查询与更新',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch07/overview', // 概述
        'mysql/ch07/task1', // 任务一 
        'mysql/ch07/task2', // 任务二 
        'mysql/ch07/task3', // 任务三 
        'mysql/ch07/task4', // 任务一 
        'mysql/ch07/task5', // 任务二 
        'mysql/ch07/task6', // 任务三 
        'mysql/ch07/demo1', // 案例 1
        'mysql/ch07/demo2', // 案例 2
      ],
    },
    // 项目八
    {
      type: 'category',
      label: '项目八  索引与视图',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch08/overview', // 概述
        'mysql/ch08/task1', // 任务一 
        'mysql/ch08/task2', // 任务二
        'mysql/ch08/exercise1', // 索引专项训练 
        'mysql/ch08/exercise2', // 视图专项训练
      ],
    },
    // 项目九
    {
      type: 'category',
      label: '项目九 数据库编程',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch09/overview', // 概述
        'mysql/ch09/task1', // 任务一 
        'mysql/ch09/task2', // 任务二 
        'mysql/ch09/task3', // 任务三
        'mysql/ch09/task4', // 任务三 
        'mysql/ch09/atta-variable', // 任务三 
        'mysql/ch09/exercise1', // 专项训练 
        'mysql/ch09/exercise2', // 专项训练 
        'mysql/ch09/exercise3', // 专项训练 
        'mysql/ch09/exercise4', // 专项训练 
      ],
    },
    // 项目十
    {
      type: 'category',
      label: '项目十 数据库设计',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch10/overview', // 概述
        'mysql/ch10/task1', // 任务一 
        'mysql/ch10/task2', // 任务二 
        'mysql/ch10/task3', // 任务三 
        'mysql/ch10/task4', // 任务一 
        'mysql/ch10/task5', // 任务二 
        'mysql/ch10/task6', // 任务三 
      ],
    },
    // 项目十一
    {
      type: 'category',
      label: '项目十一 数据库安全',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch11/overview', // 概述
        'mysql/ch11/task1', // 任务一 
        'mysql/ch11/task2', // 任务二 
        'mysql/ch11/task3', // 任务三 
        'mysql/ch11/task4', // 任务四
      ],
    },
    // 项目十二
    {
      type: 'category',
      label: '项目十二 数据库备份和恢复',
      collapsible: true,
      collapsed: false,
      items: [
        'mysql/ch12/overview', // 概述
        'mysql/ch12/task1', // 任务一 
        'mysql/ch12/task2', // 任务二 
        'mysql/ch12/task3', // 任务三 
      ],
    }
  ],
  // ============ 计算机应用基础 教程侧边栏 ============
  computerBasicSidebar: [
    {
      type: 'doc',
      id: 'computer-basics/index',  // 确保 docs/computer-basics/ch03-01.md 存在
      label: '考试大纲',
    },
    // 项目一：认识计算机
    {
      type: 'category',
      label: '项目一 认识计算机',
      collapsible: true,
      collapsed: false,
      items: [
        'computer-basics/proj1/index', // 概述
        'computer-basics/proj1/task1', // 
        'computer-basics/proj1/task2', // 
        'computer-basics/proj1/task3', // 
        'computer-basics/proj1/task4', // 
      ],
    },
    // 项目二 计算机系统
    {
      type: 'category',
      label: '项目二 计算机系统',
      collapsible: true,
      collapsed: false,
      items: [
        'computer-basics/proj2/index', // 概述
        'computer-basics/proj2/task1', // 任务一 计算机的硬件系统
        'computer-basics/proj2/task2', // 任务二 计算机的软件系统
        'computer-basics/proj2/task3', // 任务三 计算机的工作原理
        'computer-basics/proj2/task4', // 任务四 微型计算机的硬件系统
        'computer-basics/proj2/task5', // 任务五 微型计算机的主要性能指标
      ],
    },
    // 项目三 信息在计算机中的表示
    {
      type: 'category',
      label: '项目三 信息在计算机中的表示',
      collapsible: true,
      collapsed: false,
      items: [
        'computer-basics/proj3/index', // 概述
        'computer-basics/proj3/task1', // 任务一 信息的表示
        'computer-basics/proj3/task2', // 任务二 数制及其转换
        'computer-basics/proj3/task3', // 任务三 字符编码
      ],
    },
    // 项目四 计算机维护
    {
      type: 'category',
      label: '项目四 计算机维护',
      collapsible: true,
      collapsed: false,
      items: [
        'computer-basics/proj4/index', // 概述
        'computer-basics/proj4/task1', // 任务一 信息的表示
        'computer-basics/proj4/task2', // 任务二 数制及其转换
        'computer-basics/proj4/task3', //
      ],
    },
    // 项目五 中英文录入
    {
      type: 'category',
      label: '项目五 中英文录入',
      collapsible: true,
      collapsed: false,
      items: [
        'computer-basics/proj5/index', // 概述
        'computer-basics/proj5/task1', //
        'computer-basics/proj5/task2', //
      ],
    },
  ],
  // ============ 计算机网络基础 教程侧边栏 ============
  netWorkBasicSidebar: [
    {
      type: 'doc',
      id: 'ninthit/index',  // 
      label: '考试大纲',
    },
    // 模块一：计算机网络概述
    {
      type: 'category',
      label: '模块一 计算机网络概述',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit01/overview', // 概述
         {
          type: 'category',
          label: '项目一 网络发展与基本概念',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project1/task1', // 
            'ninthit/unit01/project1/task2', // 
            'ninthit/unit01/project1/task3', // 
          ],
        },
        {
          type: 'category',
          label: '项目二 网络的分类与拓扑结构',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project2/task1', // 
            'ninthit/unit01/project2/task2', // 
          ],
        }, 
        {
          type: 'category',
          label: '项目三 计算机网络传输介质',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project3/task1', // 
            'ninthit/unit01/project3/task2', // 
          ],
        }, 
        {
          type: 'category',
          label: '项目四 网络的组成功能应用',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project4/task1', // 
            'ninthit/unit01/project4/task2', // 
          ],
        }, // 任务四 计算机的前沿技术
      ],
    },
    // 模块二：数据通信基础
    {
      type: 'category',
      label: '模块二：数据通信基础',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit02/overview', // 概述
        'ninthit/unit02/project1', // 任务一 数据通信的基本概念
        'ninthit/unit02/project2', // 任务二 数据传输方式
        'ninthit/unit02/project3', // 任务三 数据交换方式
        'ninthit/unit02/project4', // 任务四 数据通信的性能指标
      ],
    },
    // 模块三: OSI参考模型体系
    {
      type: 'category',
      label: '模块三 OSI参考模型体系',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块四 TCP/IP参考模型体系
    {
      type: 'category',
      label: '模块四 TCP/IP参考模型体系',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块五 局域网技术
    {
      type: 'category',
      label: '模块五 局域网技术',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块六 局域网组网技术
    {
      type: 'category',
      label: '模块六 局域网组网技术',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块七 广域网技术概述
    {
      type: 'category',
      label: '模块七 广域网技术概述',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块八 Internet技术与应用
    {
      type: 'category',
      label: '模块八 Internet技术与应用',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块九 网络安全
    {
      type: 'category',
      label: '模块九 网络安全',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块十 网络管理与结构化布线
    {
      type: 'category',
      label: '模块十 网络管理与结构化布线',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
  ],
  // ============ 普高单招九类信息技术 教程侧边栏 ============
  ninthitSidebar: [
    {
      type: 'doc',
      id: 'ninthit/index',  // 
      label: '考试大纲',
    },
    // 模块一：计算机网络概述
    {
      type: 'category',
      label: '模块一 计算机网络概述',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit01/overview', // 概述
         {
          type: 'category',
          label: '项目一 网络发展与基本概念',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project1/task1', // 
            'ninthit/unit01/project1/task2', // 
            'ninthit/unit01/project1/task3', // 
          ],
        },
        {
          type: 'category',
          label: '项目二 网络的分类与拓扑结构',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project2/task1', // 
            'ninthit/unit01/project2/task2', // 
          ],
        }, 
        {
          type: 'category',
          label: '项目三 计算机网络传输介质',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project3/task1', // 
            'ninthit/unit01/project3/task2', // 
          ],
        }, 
        {
          type: 'category',
          label: '项目四 网络的组成功能应用',
          collapsible: true,
          collapsed: true,
          items: [
            'ninthit/unit01/project4/task1', // 
            'ninthit/unit01/project4/task2', // 
          ],
        }, // 任务四 计算机的前沿技术
      ],
    },
    // 模块二：数据通信基础
    {
      type: 'category',
      label: '模块二：数据通信基础',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit02/overview', // 概述
        'ninthit/unit02/project1', // 任务一 数据通信的基本概念
        'ninthit/unit02/project2', // 任务二 数据传输方式
        'ninthit/unit02/project3', // 任务三 数据交换方式
        'ninthit/unit02/project4', // 任务四 数据通信的性能指标
      ],
    },
    // 模块三: OSI参考模型体系
    {
      type: 'category',
      label: '模块三 OSI参考模型体系',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块四 TCP/IP参考模型体系
    {
      type: 'category',
      label: '模块四 TCP/IP参考模型体系',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块五 局域网技术
    {
      type: 'category',
      label: '模块五 局域网技术',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块六 局域网组网技术
    {
      type: 'category',
      label: '模块六 局域网组网技术',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块七 广域网技术概述
    {
      type: 'category',
      label: '模块七 广域网技术概述',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块八 Internet技术与应用
    {
      type: 'category',
      label: '模块八 Internet技术与应用',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块九 网络安全
    {
      type: 'category',
      label: '模块九 网络安全',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
    // 模块十 网络管理与结构化布线
    {
      type: 'category',
      label: '模块十 网络管理与结构化布线',
      collapsible: true,
      collapsed: false,
      items: [
        'ninthit/unit03/overview', // 概述
        'ninthit/unit03/project1', // 任务一 网络体系结构的基本概念
        'ninthit/unit03/project2', // 任务二 网络协议栈
        'ninthit/unit03/project3', // 任务三 网络拓扑结构
      ],
    },
  ],
};

export default sidebars;
